-- Preguntas Tema 12: Fundamentos de blockchain y DLT
-- Generadas: 2025-01-23
-- Total: 50 preguntas difíciles con explicaciones


INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(12, '¿Cuál es la principal diferencia entre una blockchain y una base de datos distribuida tradicional?', 
'La blockchain utiliza cifrado mientras que las bases de datos no', 
'La blockchain es inmutable por diseño mediante hash criptográfico encadenado, mientras que las bases de datos permiten modificaciones', 
'La blockchain es más rápida en procesamiento de transacciones', 
'La blockchain no requiere validación de datos',
'B',
'La característica fundamental de blockchain es su inmutabilidad lograda mediante el encadenamiento criptográfico de bloques. Cada bloque contiene el hash del bloque anterior, haciendo prácticamente imposible modificar datos históricos sin alterar toda la cadena. Las bases de datos tradicionales permiten operaciones CRUD completas.'),

(12, 'En el contexto de DLT (Distributed Ledger Technology), ¿qué significa que un sistema sea "trustless"?', 
'Que no se puede confiar en ningún participante del sistema', 
'Que el sistema no requiere autoridades centrales de confianza para validar transacciones', 
'Que todas las transacciones son anónimas', 
'Que no existe cifrado en las comunicaciones',
'B',
'Un sistema "trustless" elimina la necesidad de confiar en intermediarios o autoridades centrales. Los participantes pueden interactuar directamente confiando en el protocolo criptográfico y el mecanismo de consenso, no en terceros. Esto es fundamental en blockchain pública.'),

(12, 'En Proof of Work (PoW), ¿qué problema computacional deben resolver los mineros?', 
'Descifrar claves privadas de otros usuarios', 
'Resolver ecuaciones diferenciales complejas', 
'Encontrar un nonce que produzca un hash con un número específico de ceros iniciales', 
'Factorizar números primos grandes',
'C',
'En PoW, los mineros buscan un valor nonce que, al combinarse con los datos del bloque y aplicar una función hash (como SHA-256), produzca un resultado con cierto número de ceros iniciales. Esta dificultad ajustable garantiza un tiempo promedio entre bloques y consume recursos computacionales significativos.'),

(12, 'En Proof of Stake (PoS), ¿cómo se selecciona típicamente al validador que creará el siguiente bloque?', 
'Siempre es el que tiene más tokens en stake', 
'Se selecciona aleatoriamente ponderado por la cantidad de tokens en stake y otros factores', 
'El primero en resolver el problema criptográfico', 
'Por votación democrática de todos los participantes',
'B',
'PoS utiliza selección pseudoaleatoria ponderada por la cantidad de tokens apostados (staked). Algunos sistemas incluyen factores adicionales como edad del stake o reputación. Esto evita centralización mientras mantiene seguridad proporcional a la inversión económica del validador.'),

(12, '¿Qué es un "51% attack" en blockchain?', 
'Cuando el 51% de los usuarios abandonan la red', 
'Cuando una entidad controla más del 51% del poder de hash/stake y puede revertir transacciones', 
'Cuando el 51% de los nodos fallan simultáneamente', 
'Cuando se pierde el 51% de las claves privadas',
'B',
'Un ataque del 51% ocurre cuando una entidad controla la mayoría del poder computacional (PoW) o stake (PoS), permitiéndole reorganizar bloques, realizar double-spending y censurar transacciones. Es el principal vector de ataque contra el consenso blockchain, aunque económicamente costoso en redes grandes.'),

(12, '¿Qué caracteriza a una blockchain privada frente a una pública?', 
'Usa algoritmos de cifrado diferentes', 
'Requiere permisos para participar y típicamente tiene validadores conocidos y autorizados', 
'No utiliza criptografía', 
'Es más lenta en todas las operaciones',
'B',
'Las blockchains privadas (permissioned) requieren autorización para leer/escribir datos y participar en consenso. Los validadores son entidades conocidas, lo que permite mayor throughput y privacidad, pero sacrifica descentralización. Son comunes en entornos empresariales.'),

(12, '¿Qué es una blockchain de consorcio?', 
'Una blockchain completamente pública sin restricciones', 
'Una blockchain híbrida donde un grupo preseleccionado de nodos controla el consenso', 
'Una blockchain que solo almacena datos financieros', 
'Una blockchain sin mecanismo de consenso',
'B',
'Una blockchain de consorcio es semi-privada, donde el consenso está controlado por un grupo preseleccionado de organizaciones. Combina beneficios de blockchains públicas (transparencia entre miembros) y privadas (control de acceso), ideal para colaboración entre empresas.'),

(12, '¿Qué es un "fork" en blockchain?', 
'Una herramienta para minar criptomonedas', 
'Una divergencia en la cadena que crea dos versiones diferentes del historial', 
'Un tipo de wallet específico', 
'Un algoritmo de consenso',
'B',
'Un fork ocurre cuando la blockchain se divide en dos caminos. Puede ser temporal (orphan blocks por minado simultáneo) o permanente (hard fork por cambios de protocolo incompatibles o soft fork compatible hacia atrás). Ejemplos: Bitcoin/Bitcoin Cash.'),

(12, '¿Qué es el "double spending problem" que blockchain resuelve?', 
'Gastar dos veces el mismo presupuesto en una empresa', 
'El problema de que un activo digital pueda ser copiado y gastado múltiples veces', 
'Cobrar dos veces por el mismo servicio', 
'Duplicar claves privadas',
'B',
'El double spending es el riesgo de que un activo digital sea duplicado y gastado múltiples veces. Blockchain lo resuelve mediante consenso distribuido que establece un orden único de transacciones, haciendo que solo la primera sea válida y las copias sean rechazadas.'),

(12, '¿Qué es un nonce en el contexto de blockchain?', 
'Un número usado una sola vez en el proceso de minado para encontrar un hash válido', 
'El nombre del creador de Bitcoin', 
'Un tipo de criptomoneda', 
'Una dirección de wallet',
'A',
'El nonce (number used once) es un valor que los mineros incrementan iterativamente buscando un hash que cumpla la dificultad requerida. Es el parámetro variable en PoW que permite encontrar bloques válidos mediante fuerza bruta computacional.'),

(12, '¿Qué es el "merkle tree" o árbol de Merkle en blockchain?', 
'Un algoritmo de consenso alternativo', 
'Una estructura de datos jerárquica que permite verificar eficientemente la integridad de grandes conjuntos de transacciones', 
'Un tipo de wallet hardware', 
'Un exchange de criptomonedas',
'B',
'El árbol de Merkle es una estructura hash jerárquica donde cada nodo hoja es el hash de datos de transacción y cada nodo padre es el hash de sus hijos. El merkle root en el header del bloque permite verificar cualquier transacción con log(n) complejidad, esencial para SPV (Simple Payment Verification).'),

(12, '¿Qué diferencia fundamental existe entre Bitcoin y Ethereum en su diseño original?', 
'Bitcoin usa PoW y Ethereum siempre usó PoS', 
'Ethereum incluye una máquina virtual Turing-completa para ejecutar smart contracts, Bitcoin tiene scripting limitado', 
'Bitcoin es privado y Ethereum público', 
'No hay diferencias significativas',
'B',
'Ethereum fue diseñado como plataforma de computación descentralizada con EVM (Ethereum Virtual Machine) Turing-completa, permitiendo smart contracts complejos. Bitcoin tiene un lenguaje de scripting intencionalmentelimitado (no Turing-completo) enfocado en transacciones, priorizando seguridad y simplicidad.'),

(12, '¿Qué es un "hot wallet" y cuál es su principal riesgo?', 
'Un wallet que genera calor por el procesamiento', 
'Un wallet conectado a internet, vulnerable a ataques remotos y malware', 
'Un wallet que solo funciona en climas cálidos', 
'Un wallet sin cifrado',
'B',
'Un hot wallet está conectado a internet para facilitar transacciones frecuentes. Su principal riesgo es la exposición a ataques remotos, malware, phishing y vulnerabilidades de software. Conveniente pero menos seguro que cold wallets para almacenamiento a largo plazo.'),

(12, '¿Qué es un "cold wallet" o cold storage?', 
'Un wallet almacenado en servidores refrigerados', 
'Un wallet offline (hardware, paper wallet) que minimiza exposición a ataques remotos', 
'Un wallet que solo funciona en invierno', 
'Un wallet sin claves privadas',
'B',
'Cold storage mantiene claves privadas completamente offline (hardware wallets, paper wallets, air-gapped computers). Esto elimina vectores de ataque remoto, siendo ideal para almacenar grandes cantidades a largo plazo. Requiere más pasos para transaccionar pero maximiza seguridad.'),

(12, '¿Qué es un exchange de criptomonedas centralizado (CEX)?', 
'Un protocolo blockchain específico', 
'Una plataforma intermediaria que custodia fondos de usuarios y facilita trading de criptomonedas', 
'Un tipo de smart contract', 
'Un algoritmo de consenso',
'B',
'Un CEX es una entidad centralizada que actúa como intermediario, custodiando fondos de usuarios en wallets propios. Ofrece alta liquidez y UX familiar pero introduce riesgos de contraparte, hacks y requiere confianza. Ejemplos: Coinbase, Binance, Kraken.'),

(12, '¿Qué caracteriza a un exchange descentralizado (DEX)?', 
'Está regulado por gobiernos', 
'Permite trading peer-to-peer mediante smart contracts sin custodia de fondos', 
'Solo opera con monedas fiat', 
'Requiere KYC obligatorio',
'B',
'Un DEX opera mediante smart contracts, permitiendo trading directo entre usuarios sin intermediarios custodios. Los usuarios mantienen control de sus claves privadas. Ofrece mayor privacidad y resistencia a censura pero puede tener menor liquidez y UX más compleja. Ejemplos: Uniswap, SushiSwap.'),

(12, '¿Qué es el "gas" en Ethereum?', 
'Combustible físico para servidores', 
'Unidad que mide el costo computacional de ejecutar operaciones en la EVM', 
'Un tipo de criptomoneda alternativa', 
'El nombre del algoritmo de consenso',
'B',
'Gas mide recursos computacionales requeridos para ejecutar operaciones en Ethereum. Cada operación (almacenamiento, cálculo, transferencia) tiene un costo en gas. Los usuarios pagan gas fees en ETH para incentivar a validadores. Previene spam y loops infinitos limitando ejecución.'),

(12, '¿Qué es un "gas limit" en una transacción Ethereum?', 
'El precio máximo del gas', 
'La cantidad máxima de gas que el usuario está dispuesto a consumir en la transacción', 
'El tiempo máximo de ejecución', 
'El número máximo de validadores',
'B',
'Gas limit es el máximo de unidades de gas que una transacción puede consumir. Si la ejecución requiere más gas, falla pero el gas consumido hasta ese punto no se reembolsa. Protege contra errores costosos y permite estimar costos antes de ejecutar.'),

(12, '¿Qué es Hyperledger Fabric?', 
'Una criptomoneda competidora de Bitcoin', 
'Un framework de blockchain empresarial permissioned modular desarrollado por Linux Foundation', 
'Un exchange descentralizado', 
'Un wallet hardware',
'B',
'Hyperledger Fabric es un framework blockchain permissioned modular para aplicaciones empresariales. Ofrece arquitectura pluggable (consenso, membership), canales privados, chaincode (smart contracts) y no requiere criptomoneda nativa. Ideal para consorcios empresariales con requisitos de privacidad.'),

(12, '¿Qué es el "Byzantine Generals Problem" en sistemas distribuidos?', 
'Un problema histórico militar sin relación con tecnología', 
'El desafío de lograr consenso en sistemas distribuidos donde algunos nodos pueden ser maliciosos o fallar', 
'Un algoritmo de cifrado específico', 
'Un tipo de ataque a wallets',
'B',
'El problema de los generales bizantinos ilustra el desafío de alcanzar consenso cuando algunos participantes pueden ser maliciosos o no confiables. Los algoritmos de consenso blockchain (PoW, PoS, PBFT) son soluciones a este problema, permitiendo acuerdo en entornos adversariales.'),

(12, '¿Qué es PBFT (Practical Byzantine Fault Tolerance)?', 
'Un tipo de criptomoneda', 
'Un algoritmo de consenso que tolera hasta 1/3 de nodos maliciosos mediante votación en múltiples fases', 
'Un protocolo de cifrado', 
'Un lenguaje de programación',
'B',
'PBFT es un algoritmo de consenso que logra acuerdo en sistemas con hasta f nodos bizantinos de 3f+1 total. Usa comunicación en fases (pre-prepare, prepare, commit) entre nodos conocidos. Eficiente para blockchains permissioned pero no escala bien con muchos validadores.'),

(12, '¿Qué es el "finality" o finalidad en blockchain?', 
'El último bloque de la cadena', 
'La garantía de que una transacción confirmada no puede ser revertida', 
'El cierre de un exchange', 
'La destrucción de tokens',
'B',
'Finality es la garantía de irreversibilidad de transacciones. En PoW es probabilística (más confirmaciones = mayor seguridad). En algunos PoS y BFT es determinística (finalidad inmediata tras consenso). Crítico para aplicaciones que requieren certeza absoluta.'),

(12, '¿Qué es un "oracle" en el contexto de blockchain?', 
'Un tipo de base de datos', 
'Un servicio que proporciona datos externos del mundo real a smart contracts', 
'Un algoritmo de minado', 
'Un tipo de token',
'B',
'Los oracles son puentes entre blockchain y datos externos (precios, clima, eventos). Smart contracts no pueden acceder directamente a internet, por lo que oracles inyectan datos on-chain. El "oracle problem" es garantizar confiabilidad de estos datos. Ejemplos: Chainlink, Band Protocol.'),

(12, '¿Qué es un "sidechain"?', 
'Una blockchain secundaria interoperable con la blockchain principal mediante mecanismos de transferencia de activos', 
'Un tipo de wallet', 
'Un algoritmo de cifrado', 
'Una criptomoneda específica',
'A',
'Una sidechain es una blockchain separada vinculada a la mainchain mediante un two-way peg que permite transferir activos entre ambas. Permite experimentación, escalabilidad y funcionalidades específicas sin afectar la cadena principal. Ejemplo: Liquid Network para Bitcoin.'),

(12, '¿Qué es "sharding" en blockchain?', 
'Romper físicamente los discos duros', 
'Particionar la blockchain en fragmentos paralelos para mejorar escalabilidad y throughput', 
'Un tipo de ataque', 
'Un protocolo de cifrado',
'B',
'Sharding divide la red en shards (fragmentos) que procesan transacciones en paralelo. Cada shard mantiene un subconjunto del estado global. Mejora escalabilidad horizontal pero introduce complejidad en comunicación cross-shard y seguridad. Ethereum 2.0 implementa sharding.'),

(12, '¿Qué es una "layer 2" solution en blockchain?', 
'El segundo bloque de la cadena', 
'Protocolos construidos sobre la blockchain base para mejorar escalabilidad procesando transacciones off-chain', 
'Un tipo de minero', 
'Una criptomoneda específica',
'B',
'Layer 2 son soluciones que procesan transacciones fuera de la mainchain (layer 1) pero heredan su seguridad. Incluyen state channels, rollups (optimistic, zk), plasma. Aumentan throughput y reducen costos manteniendo descentralización. Ejemplos: Lightning Network, Polygon, Arbitrum.'),

(12, '¿Qué es el "trilemma" de blockchain?', 
'Tres tipos de criptomonedas', 
'El desafío de lograr simultáneamente descentralización, seguridad y escalabilidad', 
'Tres algoritmos de consenso', 
'Tres tipos de wallets',
'B',
'El trilemma de blockchain postula que es difícil optimizar simultáneamente: 1) Descentralización (muchos nodos independientes), 2) Seguridad (resistencia a ataques), 3) Escalabilidad (alto throughput). Típicamente se sacrifica uno para mejorar los otros. Diferentes blockchains priorizan diferentes trade-offs.'),

(12, '¿Qué es un "token" en blockchain?', 
'Una contraseña de acceso', 
'Un activo digital representado en blockchain que puede tener diversos usos (utilidad, gobernanza, valor)', 
'Un tipo de nodo', 
'Un algoritmo de minado',
'B',
'Un token es un activo digital en blockchain con reglas definidas por smart contract. Puede representar valor (security tokens), utilidad (access tokens), gobernanza (voting tokens), o activos del mundo real (tokenización). Estándares: ERC-20, ERC-721 (NFTs).'),

(12, '¿Qué diferencia hay entre "coin" y "token"?', 
'No hay diferencia, son sinónimos', 
'Coin es nativa de su blockchain (BTC, ETH), token se construye sobre blockchain existente mediante smart contracts', 
'Coin es digital, token es físico', 
'Token es más valioso que coin',
'B',
'Una coin es la criptomoneda nativa de su propia blockchain (Bitcoin en Bitcoin, Ether en Ethereum). Un token se crea sobre una blockchain existente mediante smart contracts (USDT, LINK en Ethereum). Coins tienen su propia infraestructura, tokens aprovechan infraestructura existente.'),

(12, '¿Qué es un "stablecoin"?', 
'Una criptomoneda que nunca cambia de precio', 
'Una criptomoneda diseñada para mantener valor estable respecto a un activo de referencia (USD, oro)', 
'Una blockchain muy segura', 
'Un tipo de wallet',
'B',
'Los stablecoins buscan minimizar volatilidad vinculándose a activos estables. Tipos: 1) Fiat-collateralized (USDC, USDT respaldados por USD), 2) Crypto-collateralized (DAI respaldado por ETH), 3) Algorithmic (ajuste algorítmico de supply). Facilitan pagos y trading.'),

(12, '¿Qué es el "halving" en Bitcoin?', 
'Dividir bitcoins en fracciones más pequeñas', 
'La reducción a la mitad de la recompensa de bloque que ocurre cada 210,000 bloques (~4 años)', 
'Un tipo de fork', 
'Un ataque a la red',
'B',
'El halving reduce la recompensa de minado a la mitad aproximadamente cada 4 años, controlando la emisión de nuevos bitcoins. Comenzó en 50 BTC (2009), actualmente 6.25 BTC (2024), llegará a 3.125 BTC (~2024). Crea escasez programada con supply máximo de 21 millones BTC.'),

(12, '¿Qué es "mining difficulty" en PoW?', 
'La complejidad del código de minado', 
'Un parámetro ajustable que controla cuán difícil es encontrar un hash válido, manteniendo tiempo promedio entre bloques', 
'El costo de la electricidad', 
'El número de mineros activos',
'B',
'La dificultad de minado ajusta el número de ceros requeridos en el hash del bloque. Se recalcula periódicamente (cada 2016 bloques en Bitcoin) basándose en el hashrate de la red para mantener tiempo objetivo entre bloques (10 min en Bitcoin). Más hashrate = mayor dificultad.'),

(12, '¿Qué es un "mining pool"?', 
'Una piscina donde se enfrían los equipos de minado', 
'Un grupo de mineros que combinan poder computacional y comparten recompensas proporcionalmente', 
'Un tipo de wallet', 
'Un exchange de criptomonedas',
'B',
'Los mining pools agregan hashrate de múltiples mineros para aumentar probabilidad de encontrar bloques. Las recompensas se distribuyen según contribución (PPS, PPLNS). Reduce varianza de ingresos individuales pero introduce centralización. Ejemplos: F2Pool, Antpool.'),

(12, '¿Qué es "slashing" en Proof of Stake?', 
'Reducir el precio de una criptomoneda', 
'Penalización que destruye parte del stake de un validador por comportamiento malicioso o negligente', 
'Dividir tokens en partes más pequeñas', 
'Un tipo de fork',
'B',
'Slashing es el mecanismo punitivo en PoS que confisca stake de validadores que actúan maliciosamente (double signing, downtime prolongado). Crea desincentivo económico contra ataques. La severidad varía según protocolo y tipo de infracción. Fundamental para seguridad en PoS.'),

(12, '¿Qué es un "validator" en Proof of Stake?', 
'Un programa que verifica sintaxis de código', 
'Un nodo que apuesta tokens y es seleccionado para proponer/validar bloques, recibiendo recompensas', 
'Un tipo de wallet', 
'Un exchange regulado',
'B',
'Los validadores en PoS bloquean (stake) tokens como garantía económica y son seleccionados para crear/validar bloques. Reciben recompensas por comportamiento honesto y sufren slashing por malicia. Reemplazan a mineros de PoW con menor consumo energético.'),

(12, '¿Qué es "staking" en criptomonedas?', 
'Apostar tokens en juegos de azar', 
'Bloquear tokens en un protocolo PoS para participar en consenso y ganar recompensas', 
'Vender tokens rápidamente', 
'Minar con hardware especializado',
'B',
'Staking implica bloquear tokens en un smart contract o protocolo PoS para asegurar la red. Los participantes reciben recompensas (nuevos tokens, fees) proporcionales a su stake. Puede ser directo (ejecutar validador) o delegado (a través de pools). Genera rendimiento pasivo.'),

(12, '¿Qué es "delegated Proof of Stake" (DPoS)?', 
'Un sistema donde holders votan por un número limitado de validadores que producen bloques', 
'Lo mismo que PoS tradicional', 
'Un tipo de PoW', 
'Un protocolo de cifrado',
'A',
'DPoS permite a holders de tokens votar por delegados/validadores (típicamente 21-101) que producen bloques en rotación. Ofrece mayor throughput y eficiencia que PoS puro pero con mayor centralización. Los delegados pueden ser removidos por votación. Usado en EOS, TRON.'),

(12, '¿Qué es un "genesis block"?', 
'El bloque más reciente', 
'El primer bloque de una blockchain, hardcoded sin referencia a bloque previo', 
'Un tipo de smart contract', 
'Un algoritmo de consenso',
'B',
'El genesis block es el bloque 0 o 1 de una blockchain, creado manualmente sin hash de bloque anterior. Contiene configuración inicial y parámetros de la red. En Bitcoin, el genesis block de 2009 incluye el mensaje "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks".'),

(12, '¿Qué es "block time" o tiempo de bloque?', 
'La hora en que se crea un bloque', 
'El intervalo promedio entre la creación de bloques consecutivos', 
'El tiempo que tarda en descargarse un bloque', 
'La duración de una transacción',
'B',
'Block time es el intervalo objetivo entre bloques, determinado por el protocolo. Bitcoin: ~10 minutos, Ethereum: ~12 segundos. Afecta velocidad de confirmación y throughput. Se mantiene mediante ajuste de dificultad (PoW) o parámetros de protocolo (PoS).'),

(12, '¿Qué es "block size" o tamaño de bloque?', 
'El tamaño físico del hardware', 
'El límite máximo de datos que puede contener un bloque, afectando throughput', 
'El número de mineros', 
'El precio del bloque',
'B',
'Block size limita la cantidad de datos (transacciones) por bloque. Bitcoin: 1MB (4MB con SegWit), Bitcoin Cash: 32MB. Mayor tamaño = más transacciones pero mayor carga de almacenamiento/ancho de banda, afectando descentralización. Tema controversial en debates de escalabilidad.'),

(12, '¿Qué es "transaction throughput" o rendimiento de transacciones?', 
'El costo de una transacción', 
'El número de transacciones que una blockchain puede procesar por segundo (TPS)', 
'El tiempo de una transacción individual', 
'El tamaño de una transacción',
'B',
'Throughput (TPS) mide capacidad de procesamiento. Bitcoin: ~7 TPS, Ethereum: ~15-30 TPS, Visa: ~24,000 TPS. Limitado por block size, block time y complejidad de transacciones. Mejoras: layer 2, sharding, blockchains de alto rendimiento (Solana: ~65,000 TPS teórico).'),

(12, '¿Qué es "mempool" en blockchain?', 
'Un tipo de memoria RAM especial', 
'El conjunto de transacciones no confirmadas esperando ser incluidas en un bloque', 
'Un wallet específico', 
'Un algoritmo de consenso',
'B',
'El mempool (memory pool) almacena transacciones válidas pero no confirmadas. Los mineros/validadores seleccionan transacciones del mempool (típicamente por fee más alto) para incluir en bloques. El tamaño del mempool indica congestión de red y afecta fees requeridos.'),

(12, '¿Qué es "transaction fee" o comisión de transacción?', 
'El costo de crear una wallet', 
'El pago a mineros/validadores por incluir y procesar una transacción en un bloque', 
'El precio de la criptomoneda', 
'El costo del hardware',
'B',
'Transaction fees incentivan a mineros/validadores a incluir transacciones en bloques. En Bitcoin son opcionales pero priorizadas por fee. En Ethereum (gas fees) son obligatorias y varían según complejidad computacional y congestión de red. Fuente de ingresos post-emisión.'),

(12, '¿Qué es "confirmation" o confirmación en blockchain?', 
'Un email de verificación', 
'Cada bloque añadido después del bloque que contiene una transacción, aumentando su seguridad', 
'La creación de una wallet', 
'El registro en un exchange',
'B',
'Cada bloque subsecuente tras el que contiene una transacción es una confirmación. Más confirmaciones = menor probabilidad de reversión por reorganización de cadena. Bitcoin: 6 confirmaciones (~1 hora) consideradas seguras. Exchanges requieren múltiples confirmaciones antes de acreditar depósitos.'),

(12, '¿Qué es "hash rate" en minería?', 
'El precio del hash', 
'La velocidad a la que un minero o red puede calcular hashes, medida en H/s', 
'El número de bloques', 
'El tamaño de los bloques',
'B',
'Hash rate mide poder computacional en hashes por segundo (H/s, KH/s, MH/s, GH/s, TH/s, PH/s, EH/s). Mayor hash rate = mayor probabilidad de encontrar bloques y mayor seguridad de red contra ataques. Bitcoin network: ~400 EH/s (2024). Indicador clave de salud de red PoW.'),

(12, '¿Qué es "ASIC" en el contexto de minería?', 
'Un tipo de criptomoneda', 
'Application-Specific Integrated Circuit: hardware especializado diseñado exclusivamente para minar criptomonedas específicas', 
'Un protocolo de red', 
'Un tipo de wallet',
'B',
'ASICs son chips diseñados para un algoritmo de hash específico (SHA-256 para Bitcoin, Scrypt para Litecoin). Ofrecen eficiencia y hashrate muy superiores a GPUs pero sin flexibilidad. Su existencia centraliza minería en fabricantes/pools grandes. Algunas cryptos son ASIC-resistant.'),

(12, '¿Qué significa que una blockchain sea "ASIC-resistant"?', 
'Que no puede ser minada', 
'Diseñada con algoritmos que dificultan el desarrollo de ASICs eficientes, favoreciendo minería con hardware general', 
'Que usa PoS en lugar de PoW', 
'Que es inmune a ataques',
'B',
'Blockchains ASIC-resistant usan algoritmos memory-hard (Ethash, RandomX) que requieren mucha RAM, haciendo ASICs menos ventajosos vs GPUs/CPUs. Objetivo: democratizar minería y evitar centralización. Sin embargo, eventualmente se desarrollan ASICs para algoritmos populares.'),

(12, '¿Qué es "EIP" en Ethereum?', 
'Ethereum Investment Plan', 
'Ethereum Improvement Proposal: propuestas formales para cambios en el protocolo Ethereum', 
'Ethereum Initial Price', 
'Ethereum Insurance Policy',
'B',
'EIPs son propuestas estandarizadas para mejoras de Ethereum (protocolo, estándares de tokens, procesos). Siguen proceso de revisión comunitaria. Ejemplos importantes: EIP-20 (estándar ERC-20), EIP-721 (NFTs), EIP-1559 (reforma de fees). Similar a BIPs en Bitcoin.'),

(12, '¿Qué introdujo EIP-1559 en Ethereum?', 
'Proof of Stake', 
'Un nuevo modelo de fees con base fee quemada y priority fee, haciendo fees más predecibles', 
'Smart contracts', 
'NFTs',
'B',
'EIP-1559 (London fork, 2021) reformó el mercado de fees: 1) Base fee ajustable automáticamente según congestión (quemada, reduciendo supply de ETH), 2) Priority tip opcional para validadores. Mejora UX con fees predecibles y añade presión deflacionaria a ETH.'),

(12, '¿Qué es "The Merge" en Ethereum?', 
'La fusión con otra blockchain', 
'La transición de Ethereum de Proof of Work a Proof of Stake completada en septiembre 2022', 
'Un nuevo exchange', 
'Un tipo de smart contract',
'B',
'The Merge (15 sept 2022) unió Ethereum Mainnet (execution layer) con Beacon Chain (consensus layer PoS), eliminando PoW. Redujo consumo energético ~99.95%, cambió emisión de ETH y preparó el camino para sharding. Uno de los upgrades más significativos en historia blockchain.'),

(12, '¿Qué es un "testnet" en blockchain?', 
'Un examen sobre blockchain', 
'Una red de prueba paralela donde desarrolladores pueden experimentar sin usar criptomonedas reales', 
'Un tipo de smart contract', 
'Un exchange de prueba',
'B',
'Testnets son blockchains paralelas para desarrollo y testing. Usan tokens sin valor real, permitiendo experimentación sin riesgo financiero. Ethereum: Goerli, Sepolia. Bitcoin: Testnet. Esenciales para probar smart contracts, dApps y upgrades de protocolo antes de mainnet.');




