-- Preguntas Tema 12: Fundamentos de blockchain y DLT
-- Generadas: 2025-01-23
-- Actualizadas: 2025-12-31
-- Total: 100 preguntas difíciles con explicaciones


INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(12, '¿Cuál es la principal diferencia entre una blockchain y una base de datos distribuida tradicional?', 
'La blockchain utiliza cifrado mientras que las bases de datos no', 
'La blockchain es inmutable por diseño mediante hash criptográfico encadenado, mientras que las bases de datos permiten modificaciones', 
'La blockchain es más rápida en procesamiento de transacciones', 
'La blockchain no requiere validación de datos',
'B',
'La característica fundamental de blockchain es su inmutabilidad lograda mediante el encadenamiento criptográfico de bloques. Cada bloque contiene el hash del bloque anterior, haciendo prácticamente imposible modificar datos históricos sin alterar toda la cadena. Las bases de datos tradicionales permiten operaciones CRUD completas.'),

(12, 'En el contexto de DLT (Distributed Ledger Technology), ¿qué significa que un sistema sea "trustless"?', 
'Que no se puede confiar en ningún participante del sistema', 
'Que el sistema no requiere autoridades centrales de confianza para validar transacciones', 
'Que todas las transacciones son anónimas', 
'Que no existe cifrado en las comunicaciones',
'B',
'Un sistema "trustless" elimina la necesidad de confiar en intermediarios o autoridades centrales. Los participantes pueden interactuar directamente confiando en el protocolo criptográfico y el mecanismo de consenso, no en terceros. Esto es fundamental en blockchain pública.'),

(12, 'En Proof of Work (PoW), ¿qué problema computacional deben resolver los mineros?', 
'Descifrar claves privadas de otros usuarios', 
'Resolver ecuaciones diferenciales complejas', 
'Encontrar un nonce que produzca un hash con un número específico de ceros iniciales', 
'Factorizar números primos grandes',
'C',
'En PoW, los mineros buscan un valor nonce que, al combinarse con los datos del bloque y aplicar una función hash (como SHA-256), produzca un resultado con cierto número de ceros iniciales. Esta dificultad ajustable garantiza un tiempo promedio entre bloques y consume recursos computacionales significativos.'),

(12, 'En Proof of Stake (PoS), ¿cómo se selecciona típicamente al validador que creará el siguiente bloque?', 
'Siempre es el que tiene más tokens en stake', 
'Se selecciona aleatoriamente ponderado por la cantidad de tokens en stake y otros factores', 
'El primero en resolver el problema criptográfico', 
'Por votación democrática de todos los participantes',
'B',
'PoS utiliza selección pseudoaleatoria ponderada por la cantidad de tokens apostados (staked). Algunos sistemas incluyen factores adicionales como edad del stake o reputación. Esto evita centralización mientras mantiene seguridad proporcional a la inversión económica del validador.'),

(12, '¿Qué es un "51% attack" en blockchain?', 
'Cuando el 51% de los usuarios abandonan la red', 
'Cuando una entidad controla más del 51% del poder de hash/stake y puede revertir transacciones', 
'Cuando el 51% de los nodos fallan simultáneamente', 
'Cuando se pierde el 51% de las claves privadas',
'B',
'Un ataque del 51% ocurre cuando una entidad controla la mayoría del poder computacional (PoW) o stake (PoS), permitiéndole reorganizar bloques, realizar double-spending y censurar transacciones. Es el principal vector de ataque contra el consenso blockchain, aunque económicamente costoso en redes grandes.'),

(12, '¿Qué caracteriza a una blockchain privada frente a una pública?', 
'Usa algoritmos de cifrado diferentes', 
'Requiere permisos para participar y típicamente tiene validadores conocidos y autorizados', 
'No utiliza criptografía', 
'Es más lenta en todas las operaciones',
'B',
'Las blockchains privadas (permissioned) requieren autorización para leer/escribir datos y participar en consenso. Los validadores son entidades conocidas, lo que permite mayor throughput y privacidad, pero sacrifica descentralización. Son comunes en entornos empresariales.'),

(12, '¿Qué es una blockchain de consorcio?', 
'Una blockchain completamente pública sin restricciones', 
'Una blockchain híbrida donde un grupo preseleccionado de nodos controla el consenso', 
'Una blockchain que solo almacena datos financieros', 
'Una blockchain sin mecanismo de consenso',
'B',
'Una blockchain de consorcio es semi-privada, donde el consenso está controlado por un grupo preseleccionado de organizaciones. Combina beneficios de blockchains públicas (transparencia entre miembros) y privadas (control de acceso), ideal para colaboración entre empresas.'),

(12, '¿Qué es un "fork" en blockchain?', 
'Una herramienta para minar criptomonedas', 
'Una divergencia en la cadena que crea dos versiones diferentes del historial', 
'Un tipo de wallet específico', 
'Un algoritmo de consenso',
'B',
'Un fork ocurre cuando la blockchain se divide en dos caminos. Puede ser temporal (orphan blocks por minado simultáneo) o permanente (hard fork por cambios de protocolo incompatibles o soft fork compatible hacia atrás). Ejemplos: Bitcoin/Bitcoin Cash.'),

(12, '¿Qué es el "double spending problem" que blockchain resuelve?', 
'Gastar dos veces el mismo presupuesto en una empresa', 
'El problema de que un activo digital pueda ser copiado y gastado múltiples veces', 
'Cobrar dos veces por el mismo servicio', 
'Duplicar claves privadas',
'B',
'El double spending es el riesgo de que un activo digital sea duplicado y gastado múltiples veces. Blockchain lo resuelve mediante consenso distribuido que establece un orden único de transacciones, haciendo que solo la primera sea válida y las copias sean rechazadas.'),

(12, '¿Qué es un nonce en el contexto de blockchain?', 
'Un número usado una sola vez en el proceso de minado para encontrar un hash válido', 
'El nombre del creador de Bitcoin', 
'Un tipo de criptomoneda', 
'Una dirección de wallet',
'A',
'El nonce (number used once) es un valor que los mineros incrementan iterativamente buscando un hash que cumpla la dificultad requerida. Es el parámetro variable en PoW que permite encontrar bloques válidos mediante fuerza bruta computacional.'),

(12, '¿Qué es el "merkle tree" o árbol de Merkle en blockchain?', 
'Un algoritmo de consenso alternativo', 
'Una estructura de datos jerárquica que permite verificar eficientemente la integridad de grandes conjuntos de transacciones', 
'Un tipo de wallet hardware', 
'Un exchange de criptomonedas',
'B',
'El árbol de Merkle es una estructura hash jerárquica donde cada nodo hoja es el hash de datos de transacción y cada nodo padre es el hash de sus hijos. El merkle root en el header del bloque permite verificar cualquier transacción con log(n) complejidad, esencial para SPV (Simple Payment Verification).'),

(12, '¿Qué diferencia fundamental existe entre Bitcoin y Ethereum en su diseño original?', 
'Bitcoin usa PoW y Ethereum siempre usó PoS', 
'Ethereum incluye una máquina virtual Turing-completa para ejecutar smart contracts, Bitcoin tiene scripting limitado', 
'Bitcoin es privado y Ethereum público', 
'No hay diferencias significativas',
'B',
'Ethereum fue diseñado como plataforma de computación descentralizada con EVM (Ethereum Virtual Machine) Turing-completa, permitiendo smart contracts complejos. Bitcoin tiene un lenguaje de scripting intencionalmentelimitado (no Turing-completo) enfocado en transacciones, priorizando seguridad y simplicidad.'),

(12, '¿Qué es un "hot wallet" y cuál es su principal riesgo?', 
'Un wallet que genera calor por el procesamiento', 
'Un wallet conectado a internet, vulnerable a ataques remotos y malware', 
'Un wallet que solo funciona en climas cálidos', 
'Un wallet sin cifrado',
'B',
'Un hot wallet está conectado a internet para facilitar transacciones frecuentes. Su principal riesgo es la exposición a ataques remotos, malware, phishing y vulnerabilidades de software. Conveniente pero menos seguro que cold wallets para almacenamiento a largo plazo.'),

(12, '¿Qué es un "cold wallet" o cold storage?', 
'Un wallet almacenado en servidores refrigerados', 
'Un wallet offline (hardware, paper wallet) que minimiza exposición a ataques remotos', 
'Un wallet que solo funciona en invierno', 
'Un wallet sin claves privadas',
'B',
'Cold storage mantiene claves privadas completamente offline (hardware wallets, paper wallets, air-gapped computers). Esto elimina vectores de ataque remoto, siendo ideal para almacenar grandes cantidades a largo plazo. Requiere más pasos para transaccionar pero maximiza seguridad.'),

(12, '¿Qué es un exchange de criptomonedas centralizado (CEX)?', 
'Un protocolo blockchain específico', 
'Una plataforma intermediaria que custodia fondos de usuarios y facilita trading de criptomonedas', 
'Un tipo de smart contract', 
'Un algoritmo de consenso',
'B',
'Un CEX es una entidad centralizada que actúa como intermediario, custodiando fondos de usuarios en wallets propios. Ofrece alta liquidez y UX familiar pero introduce riesgos de contraparte, hacks y requiere confianza. Ejemplos: Coinbase, Binance, Kraken.'),

(12, '¿Qué caracteriza a un exchange descentralizado (DEX)?', 
'Está regulado por gobiernos', 
'Permite trading peer-to-peer mediante smart contracts sin custodia de fondos', 
'Solo opera con monedas fiat', 
'Requiere KYC obligatorio',
'B',
'Un DEX opera mediante smart contracts, permitiendo trading directo entre usuarios sin intermediarios custodios. Los usuarios mantienen control de sus claves privadas. Ofrece mayor privacidad y resistencia a censura pero puede tener menor liquidez y UX más compleja. Ejemplos: Uniswap, SushiSwap.'),

(12, '¿Qué es el "gas" en Ethereum?', 
'Combustible físico para servidores', 
'Unidad que mide el costo computacional de ejecutar operaciones en la EVM', 
'Un tipo de criptomoneda alternativa', 
'El nombre del algoritmo de consenso',
'B',
'Gas mide recursos computacionales requeridos para ejecutar operaciones en Ethereum. Cada operación (almacenamiento, cálculo, transferencia) tiene un costo en gas. Los usuarios pagan gas fees en ETH para incentivar a validadores. Previene spam y loops infinitos limitando ejecución.'),

(12, '¿Qué es un "gas limit" en una transacción Ethereum?', 
'El precio máximo del gas', 
'La cantidad máxima de gas que el usuario está dispuesto a consumir en la transacción', 
'El tiempo máximo de ejecución', 
'El número máximo de validadores',
'B',
'Gas limit es el máximo de unidades de gas que una transacción puede consumir. Si la ejecución requiere más gas, falla pero el gas consumido hasta ese punto no se reembolsa. Protege contra errores costosos y permite estimar costos antes de ejecutar.'),

(12, '¿Qué es Hyperledger Fabric?', 
'Una criptomoneda competidora de Bitcoin', 
'Un framework de blockchain empresarial permissioned modular desarrollado por Linux Foundation', 
'Un exchange descentralizado', 
'Un wallet hardware',
'B',
'Hyperledger Fabric es un framework blockchain permissioned modular para aplicaciones empresariales. Ofrece arquitectura pluggable (consenso, membership), canales privados, chaincode (smart contracts) y no requiere criptomoneda nativa. Ideal para consorcios empresariales con requisitos de privacidad.'),

(12, '¿Qué es el "Byzantine Generals Problem" en sistemas distribuidos?', 
'Un problema histórico militar sin relación con tecnología', 
'El desafío de lograr consenso en sistemas distribuidos donde algunos nodos pueden ser maliciosos o fallar', 
'Un algoritmo de cifrado específico', 
'Un tipo de ataque a wallets',
'B',
'El problema de los generales bizantinos ilustra el desafío de alcanzar consenso cuando algunos participantes pueden ser maliciosos o no confiables. Los algoritmos de consenso blockchain (PoW, PoS, PBFT) son soluciones a este problema, permitiendo acuerdo en entornos adversariales.'),

(12, '¿Qué es PBFT (Practical Byzantine Fault Tolerance)?', 
'Un tipo de criptomoneda', 
'Un algoritmo de consenso que tolera hasta 1/3 de nodos maliciosos mediante votación en múltiples fases', 
'Un protocolo de cifrado', 
'Un lenguaje de programación',
'B',
'PBFT es un algoritmo de consenso que logra acuerdo en sistemas con hasta f nodos bizantinos de 3f+1 total. Usa comunicación en fases (pre-prepare, prepare, commit) entre nodos conocidos. Eficiente para blockchains permissioned pero no escala bien con muchos validadores.'),

(12, '¿Qué es el "finality" o finalidad en blockchain?', 
'El último bloque de la cadena', 
'La garantía de que una transacción confirmada no puede ser revertida', 
'El cierre de un exchange', 
'La destrucción de tokens',
'B',
'Finality es la garantía de irreversibilidad de transacciones. En PoW es probabilística (más confirmaciones = mayor seguridad). En algunos PoS y BFT es determinística (finalidad inmediata tras consenso). Crítico para aplicaciones que requieren certeza absoluta.'),

(12, '¿Qué es un "oracle" en el contexto de blockchain?', 
'Un tipo de base de datos', 
'Un servicio que proporciona datos externos del mundo real a smart contracts', 
'Un algoritmo de minado', 
'Un tipo de token',
'B',
'Los oracles son puentes entre blockchain y datos externos (precios, clima, eventos). Smart contracts no pueden acceder directamente a internet, por lo que oracles inyectan datos on-chain. El "oracle problem" es garantizar confiabilidad de estos datos. Ejemplos: Chainlink, Band Protocol.'),

(12, '¿Qué es un "sidechain"?', 
'Una blockchain secundaria interoperable con la blockchain principal mediante mecanismos de transferencia de activos', 
'Un tipo de wallet', 
'Un algoritmo de cifrado', 
'Una criptomoneda específica',
'A',
'Una sidechain es una blockchain separada vinculada a la mainchain mediante un two-way peg que permite transferir activos entre ambas. Permite experimentación, escalabilidad y funcionalidades específicas sin afectar la cadena principal. Ejemplo: Liquid Network para Bitcoin.'),

(12, '¿Qué es "sharding" en blockchain?', 
'Romper físicamente los discos duros', 
'Particionar la blockchain en fragmentos paralelos para mejorar escalabilidad y throughput', 
'Un tipo de ataque', 
'Un protocolo de cifrado',
'B',
'Sharding divide la red en shards (fragmentos) que procesan transacciones en paralelo. Cada shard mantiene un subconjunto del estado global. Mejora escalabilidad horizontal pero introduce complejidad en comunicación cross-shard y seguridad. Ethereum 2.0 implementa sharding.'),

(12, '¿Qué es una "layer 2" solution en blockchain?', 
'El segundo bloque de la cadena', 
'Protocolos construidos sobre la blockchain base para mejorar escalabilidad procesando transacciones off-chain', 
'Un tipo de minero', 
'Una criptomoneda específica',
'B',
'Layer 2 son soluciones que procesan transacciones fuera de la mainchain (layer 1) pero heredan su seguridad. Incluyen state channels, rollups (optimistic, zk), plasma. Aumentan throughput y reducen costos manteniendo descentralización. Ejemplos: Lightning Network, Polygon, Arbitrum.'),

(12, '¿Qué es el "trilemma" de blockchain?', 
'Tres tipos de criptomonedas', 
'El desafío de lograr simultáneamente descentralización, seguridad y escalabilidad', 
'Tres algoritmos de consenso', 
'Tres tipos de wallets',
'B',
'El trilemma de blockchain postula que es difícil optimizar simultáneamente: 1) Descentralización (muchos nodos independientes), 2) Seguridad (resistencia a ataques), 3) Escalabilidad (alto throughput). Típicamente se sacrifica uno para mejorar los otros. Diferentes blockchains priorizan diferentes trade-offs.'),

(12, '¿Qué es un "token" en blockchain?', 
'Una contraseña de acceso', 
'Un activo digital representado en blockchain que puede tener diversos usos (utilidad, gobernanza, valor)', 
'Un tipo de nodo', 
'Un algoritmo de minado',
'B',
'Un token es un activo digital en blockchain con reglas definidas por smart contract. Puede representar valor (security tokens), utilidad (access tokens), gobernanza (voting tokens), o activos del mundo real (tokenización). Estándares: ERC-20, ERC-721 (NFTs).'),

(12, '¿Qué diferencia hay entre "coin" y "token"?', 
'No hay diferencia, son sinónimos', 
'Coin es nativa de su blockchain (BTC, ETH), token se construye sobre blockchain existente mediante smart contracts', 
'Coin es digital, token es físico', 
'Token es más valioso que coin',
'B',
'Una coin es la criptomoneda nativa de su propia blockchain (Bitcoin en Bitcoin, Ether en Ethereum). Un token se crea sobre una blockchain existente mediante smart contracts (USDT, LINK en Ethereum). Coins tienen su propia infraestructura, tokens aprovechan infraestructura existente.'),

(12, '¿Qué es un "stablecoin"?', 
'Una criptomoneda que nunca cambia de precio', 
'Una criptomoneda diseñada para mantener valor estable respecto a un activo de referencia (USD, oro)', 
'Una blockchain muy segura', 
'Un tipo de wallet',
'B',
'Los stablecoins buscan minimizar volatilidad vinculándose a activos estables. Tipos: 1) Fiat-collateralized (USDC, USDT respaldados por USD), 2) Crypto-collateralized (DAI respaldado por ETH), 3) Algorithmic (ajuste algorítmico de supply). Facilitan pagos y trading.'),

(12, '¿Qué es el "halving" en Bitcoin?', 
'Dividir bitcoins en fracciones más pequeñas', 
'La reducción a la mitad de la recompensa de bloque que ocurre cada 210,000 bloques (~4 años)', 
'Un tipo de fork', 
'Un ataque a la red',
'B',
'El halving reduce la recompensa de minado a la mitad aproximadamente cada 4 años, controlando la emisión de nuevos bitcoins. Comenzó en 50 BTC (2009), actualmente 6.25 BTC (2024), llegará a 3.125 BTC (~2024). Crea escasez programada con supply máximo de 21 millones BTC.'),

(12, '¿Qué es "mining difficulty" en PoW?', 
'La complejidad del código de minado', 
'Un parámetro ajustable que controla cuán difícil es encontrar un hash válido, manteniendo tiempo promedio entre bloques', 
'El costo de la electricidad', 
'El número de mineros activos',
'B',
'La dificultad de minado ajusta el número de ceros requeridos en el hash del bloque. Se recalcula periódicamente (cada 2016 bloques en Bitcoin) basándose en el hashrate de la red para mantener tiempo objetivo entre bloques (10 min en Bitcoin). Más hashrate = mayor dificultad.'),

(12, '¿Qué es un "mining pool"?', 
'Una piscina donde se enfrían los equipos de minado', 
'Un grupo de mineros que combinan poder computacional y comparten recompensas proporcionalmente', 
'Un tipo de wallet', 
'Un exchange de criptomonedas',
'B',
'Los mining pools agregan hashrate de múltiples mineros para aumentar probabilidad de encontrar bloques. Las recompensas se distribuyen según contribución (PPS, PPLNS). Reduce varianza de ingresos individuales pero introduce centralización. Ejemplos: F2Pool, Antpool.'),

(12, '¿Qué es "slashing" en Proof of Stake?', 
'Reducir el precio de una criptomoneda', 
'Penalización que destruye parte del stake de un validador por comportamiento malicioso o negligente', 
'Dividir tokens en partes más pequeñas', 
'Un tipo de fork',
'B',
'Slashing es el mecanismo punitivo en PoS que confisca stake de validadores que actúan maliciosamente (double signing, downtime prolongado). Crea desincentivo económico contra ataques. La severidad varía según protocolo y tipo de infracción. Fundamental para seguridad en PoS.'),

(12, '¿Qué es un "validator" en Proof of Stake?', 
'Un programa que verifica sintaxis de código', 
'Un nodo que apuesta tokens y es seleccionado para proponer/validar bloques, recibiendo recompensas', 
'Un tipo de wallet', 
'Un exchange regulado',
'B',
'Los validadores en PoS bloquean (stake) tokens como garantía económica y son seleccionados para crear/validar bloques. Reciben recompensas por comportamiento honesto y sufren slashing por malicia. Reemplazan a mineros de PoW con menor consumo energético.'),

(12, '¿Qué es "staking" en criptomonedas?', 
'Apostar tokens en juegos de azar', 
'Bloquear tokens en un protocolo PoS para participar en consenso y ganar recompensas', 
'Vender tokens rápidamente', 
'Minar con hardware especializado',
'B',
'Staking implica bloquear tokens en un smart contract o protocolo PoS para asegurar la red. Los participantes reciben recompensas (nuevos tokens, fees) proporcionales a su stake. Puede ser directo (ejecutar validador) o delegado (a través de pools). Genera rendimiento pasivo.'),

(12, '¿Qué es "delegated Proof of Stake" (DPoS)?', 
'Un sistema donde holders votan por un número limitado de validadores que producen bloques', 
'Lo mismo que PoS tradicional', 
'Un tipo de PoW', 
'Un protocolo de cifrado',
'A',
'DPoS permite a holders de tokens votar por delegados/validadores (típicamente 21-101) que producen bloques en rotación. Ofrece mayor throughput y eficiencia que PoS puro pero con mayor centralización. Los delegados pueden ser removidos por votación. Usado en EOS, TRON.'),

(12, '¿Qué es un "genesis block"?', 
'El bloque más reciente', 
'El primer bloque de una blockchain, hardcoded sin referencia a bloque previo', 
'Un tipo de smart contract', 
'Un algoritmo de consenso',
'B',
'El genesis block es el bloque 0 o 1 de una blockchain, creado manualmente sin hash de bloque anterior. Contiene configuración inicial y parámetros de la red. En Bitcoin, el genesis block de 2009 incluye el mensaje "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks".'),

(12, '¿Qué es "block time" o tiempo de bloque?', 
'La hora en que se crea un bloque', 
'El intervalo promedio entre la creación de bloques consecutivos', 
'El tiempo que tarda en descargarse un bloque', 
'La duración de una transacción',
'B',
'Block time es el intervalo objetivo entre bloques, determinado por el protocolo. Bitcoin: ~10 minutos, Ethereum: ~12 segundos. Afecta velocidad de confirmación y throughput. Se mantiene mediante ajuste de dificultad (PoW) o parámetros de protocolo (PoS).'),

(12, '¿Qué es "block size" o tamaño de bloque?', 
'El tamaño físico del hardware', 
'El límite máximo de datos que puede contener un bloque, afectando throughput', 
'El número de mineros', 
'El precio del bloque',
'B',
'Block size limita la cantidad de datos (transacciones) por bloque. Bitcoin: 1MB (4MB con SegWit), Bitcoin Cash: 32MB. Mayor tamaño = más transacciones pero mayor carga de almacenamiento/ancho de banda, afectando descentralización. Tema controversial en debates de escalabilidad.'),

(12, '¿Qué es "transaction throughput" o rendimiento de transacciones?', 
'El costo de una transacción', 
'El número de transacciones que una blockchain puede procesar por segundo (TPS)', 
'El tiempo de una transacción individual', 
'El tamaño de una transacción',
'B',
'Throughput (TPS) mide capacidad de procesamiento. Bitcoin: ~7 TPS, Ethereum: ~15-30 TPS, Visa: ~24,000 TPS. Limitado por block size, block time y complejidad de transacciones. Mejoras: layer 2, sharding, blockchains de alto rendimiento (Solana: ~65,000 TPS teórico).'),

(12, '¿Qué es "mempool" en blockchain?', 
'Un tipo de memoria RAM especial', 
'El conjunto de transacciones no confirmadas esperando ser incluidas en un bloque', 
'Un wallet específico', 
'Un algoritmo de consenso',
'B',
'El mempool (memory pool) almacena transacciones válidas pero no confirmadas. Los mineros/validadores seleccionan transacciones del mempool (típicamente por fee más alto) para incluir en bloques. El tamaño del mempool indica congestión de red y afecta fees requeridos.'),

(12, '¿Qué es "transaction fee" o comisión de transacción?', 
'El costo de crear una wallet', 
'El pago a mineros/validadores por incluir y procesar una transacción en un bloque', 
'El precio de la criptomoneda', 
'El costo del hardware',
'B',
'Transaction fees incentivan a mineros/validadores a incluir transacciones en bloques. En Bitcoin son opcionales pero priorizadas por fee. En Ethereum (gas fees) son obligatorias y varían según complejidad computacional y congestión de red. Fuente de ingresos post-emisión.'),

(12, '¿Qué es "confirmation" o confirmación en blockchain?', 
'Un email de verificación', 
'Cada bloque añadido después del bloque que contiene una transacción, aumentando su seguridad', 
'La creación de una wallet', 
'El registro en un exchange',
'B',
'Cada bloque subsecuente tras el que contiene una transacción es una confirmación. Más confirmaciones = menor probabilidad de reversión por reorganización de cadena. Bitcoin: 6 confirmaciones (~1 hora) consideradas seguras. Exchanges requieren múltiples confirmaciones antes de acreditar depósitos.'),

(12, '¿Qué es "hash rate" en minería?', 
'El precio del hash', 
'La velocidad a la que un minero o red puede calcular hashes, medida en H/s', 
'El número de bloques', 
'El tamaño de los bloques',
'B',
'Hash rate mide poder computacional en hashes por segundo (H/s, KH/s, MH/s, GH/s, TH/s, PH/s, EH/s). Mayor hash rate = mayor probabilidad de encontrar bloques y mayor seguridad de red contra ataques. Bitcoin network: ~400 EH/s (2024). Indicador clave de salud de red PoW.'),

(12, '¿Qué es "ASIC" en el contexto de minería?', 
'Un tipo de criptomoneda', 
'Application-Specific Integrated Circuit: hardware especializado diseñado exclusivamente para minar criptomonedas específicas', 
'Un protocolo de red', 
'Un tipo de wallet',
'B',
'ASICs son chips diseñados para un algoritmo de hash específico (SHA-256 para Bitcoin, Scrypt para Litecoin). Ofrecen eficiencia y hashrate muy superiores a GPUs pero sin flexibilidad. Su existencia centraliza minería en fabricantes/pools grandes. Algunas cryptos son ASIC-resistant.'),

(12, '¿Qué significa que una blockchain sea "ASIC-resistant"?', 
'Que no puede ser minada', 
'Diseñada con algoritmos que dificultan el desarrollo de ASICs eficientes, favoreciendo minería con hardware general', 
'Que usa PoS en lugar de PoW', 
'Que es inmune a ataques',
'B',
'Blockchains ASIC-resistant usan algoritmos memory-hard (Ethash, RandomX) que requieren mucha RAM, haciendo ASICs menos ventajosos vs GPUs/CPUs. Objetivo: democratizar minería y evitar centralización. Sin embargo, eventualmente se desarrollan ASICs para algoritmos populares.'),

(12, '¿Qué es "EIP" en Ethereum?', 
'Ethereum Investment Plan', 
'Ethereum Improvement Proposal: propuestas formales para cambios en el protocolo Ethereum', 
'Ethereum Initial Price', 
'Ethereum Insurance Policy',
'B',
'EIPs son propuestas estandarizadas para mejoras de Ethereum (protocolo, estándares de tokens, procesos). Siguen proceso de revisión comunitaria. Ejemplos importantes: EIP-20 (estándar ERC-20), EIP-721 (NFTs), EIP-1559 (reforma de fees). Similar a BIPs en Bitcoin.'),

(12, '¿Qué introdujo EIP-1559 en Ethereum?', 
'Proof of Stake', 
'Un nuevo modelo de fees con base fee quemada y priority fee, haciendo fees más predecibles', 
'Smart contracts', 
'NFTs',
'B',
'EIP-1559 (London fork, 2021) reformó el mercado de fees: 1) Base fee ajustable automáticamente según congestión (quemada, reduciendo supply de ETH), 2) Priority tip opcional para validadores. Mejora UX con fees predecibles y añade presión deflacionaria a ETH.'),

(12, '¿Qué es "The Merge" en Ethereum?', 
'La fusión con otra blockchain', 
'La transición de Ethereum de Proof of Work a Proof of Stake completada en septiembre 2022', 
'Un nuevo exchange', 
'Un tipo de smart contract',
'B',
'The Merge (15 sept 2022) unió Ethereum Mainnet (execution layer) con Beacon Chain (consensus layer PoS), eliminando PoW. Redujo consumo energético ~99.95%, cambió emisión de ETH y preparó el camino para sharding. Uno de los upgrades más significativos en historia blockchain.'),

(12, '¿Qué es un "testnet" en blockchain?', 
'Un examen sobre blockchain', 
'Una red de prueba paralela donde desarrolladores pueden experimentar sin usar criptomonedas reales', 
'Un tipo de smart contract', 
'Un exchange de prueba',
'B',
'Testnets son blockchains paralelas para desarrollo y testing. Usan tokens sin valor real, permitiendo experimentación sin riesgo financiero. Ethereum: Goerli, Sepolia. Bitcoin: Testnet. Esenciales para probar smart contracts, dApps y upgrades de protocolo antes de mainnet.');





-- NUEVAS PREGUNTAS AÑADIDAS (51-70)

INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(12, '¿Cuál es la principal ventaja del merkle root en la estructura de un bloque?', 
'Facilita la verificación de integridad de transacciones sin descargar el bloque completo', 
'Permite cifrar todas las transacciones del bloque', 
'Acelera el proceso de minado', 
'Reduce el tamaño del bloque automáticamente',
'A',
'El merkle root es un hash que representa todas las transacciones del bloque mediante una estructura de árbol. Permite a nodos ligeros (SPV) verificar que una transacción específica está incluida en un bloque sin descargar todas las transacciones, solo necesitando el merkle path correspondiente.'),

(12, '¿Qué diferencia fundamental existe entre el gas limit y el gas price en Ethereum?', 
'Gas limit es el precio máximo, gas price es la cantidad máxima', 
'No hay diferencia, son términos sinónimos', 
'Gas limit es la cantidad máxima de gas a consumir, gas price es lo que pagas por unidad de gas', 
'Gas limit se usa en PoW, gas price en PoS',
'C',
'Gas limit establece el máximo de unidades de gas que una transacción puede consumir (protección contra loops infinitos). Gas price es el precio por unidad de gas en gwei. El costo total es gas_usado × gas_price. Si se excede el gas limit, la transacción falla pero se cobra el gas consumido.'),

(12, '¿Cuál es la principal diferencia entre un canal privado en Hyperledger Fabric y una blockchain privada tradicional?', 
'Los canales no usan criptografía', 
'Los canales son más lentos que las blockchains privadas', 
'No hay diferencia significativa',
'Los canales permiten múltiples subredes privadas dentro de la misma infraestructura',
'D',
'Los canales en Hyperledger Fabric permiten crear múltiples ledgers privados dentro de la misma red, donde solo los miembros autorizados pueden ver las transacciones de ese canal. Esto permite privacidad granular y compartimentación de datos entre diferentes grupos de participantes en la misma infraestructura.'),

(12, '¿Qué problema específico resuelve el algoritmo de consenso Raft en Hyperledger Fabric?', 
'Proporciona consenso eficiente en entornos permissioned con tolerancia a fallos de crash', 
'Elimina la necesidad de validadores', 
'Permite minería descentralizada', 
'Reduce el consumo energético a cero',
'A',
'Raft es un algoritmo de consenso crash fault tolerant (no bizantino) que funciona mediante elección de líder. Tolera hasta (n-1)/2 fallos de n nodos. Es más simple que PBFT y eficiente para entornos permissioned donde los nodos son conocidos y no se esperan comportamientos maliciosos.'),

(12, '¿Cuál es la principal ventaja de usar chaincode en Hyperledger Fabric frente a smart contracts en Ethereum?', 
'Chaincode es más rápido porque no usa gas', 
'Chaincode no requiere programación', 
'Chaincode se ejecuta en contenedores aislados y permite mayor control sobre recursos y privacidad', 
'Chaincode es inmutable mientras que smart contracts no',
'C',
'Chaincode se ejecuta en contenedores Docker aislados, permitiendo mejor control de recursos, seguridad y privacidad. No requiere gas fees y puede acceder a bases de datos externas. Los smart contracts de Ethereum ejecutan en la EVM con limitaciones de recursos y sin acceso externo directo.'),

(12, '¿Qué característica distingue a una wallet multisig de una wallet tradicional?', 
'Puede almacenar múltiples criptomonedas', 
'Tiene mayor capacidad de almacenamiento', 
'Es más rápida en las transacciones',
'Requiere múltiples firmas de diferentes claves privadas para autorizar transacciones',
'D',
'Una wallet multisig (multi-signature) requiere un número mínimo de firmas de un conjunto de claves privadas para ejecutar transacciones (ej: 2-de-3, 3-de-5). Proporciona mayor seguridad y control distribuido, siendo ideal para organizaciones o fondos compartidos donde se requiere consenso.'),

(12, '¿Cuál es la diferencia principal entre un exchange centralizado (CEX) y uno descentralizado (DEX) en términos de custodia?', 
'CEX custodia los fondos de usuarios, DEX permite que usuarios mantengan control de sus claves', 
'CEX usa blockchain, DEX no', 
'DEX es más rápido que CEX', 
'No hay diferencia en custodia',
'A',
'En un CEX, el exchange controla las claves privadas y custodia los fondos (modelo custodial). En un DEX, los usuarios mantienen control de sus claves privadas y los fondos permanecen en sus wallets hasta el momento exacto del intercambio mediante smart contracts (modelo no-custodial).'),

(12, '¿Qué es el "slippage" en el contexto de exchanges descentralizados?', 
'El tiempo que tarda en ejecutarse una transacción', 
'La diferencia entre el precio esperado y el precio real de ejecución de una orden', 
'La comisión cobrada por el DEX', 
'El error en el cálculo de gas',
'B',
'Slippage es la diferencia entre el precio esperado al enviar una orden y el precio real al ejecutarse. Ocurre especialmente en DEX con liquidez limitada o órdenes grandes que mueven significativamente el precio. Los usuarios pueden establecer tolerancia máxima de slippage para protegerse.'),

(12, '¿Cuál es la principal función del Membership Service Provider (MSP) en Hyperledger Fabric?', 
'Minar nuevos bloques', 
'Almacenar transacciones', 
'Gestionar identidades digitales y certificados de los participantes de la red', 
'Calcular gas fees',
'C',
'El MSP gestiona identidades digitales mediante certificados X.509, definiendo quién puede participar en la red y con qué permisos. Proporciona autenticación, autorización y gestión de roles, siendo fundamental para el modelo permissioned de Hyperledger Fabric.'),

(12, '¿Qué ventaja ofrece el modelo "execute-order-validate" de Hyperledger Fabric frente al modelo tradicional "order-execute"?', 
'Es más rápido en todos los casos', 
'No requiere validadores', 
'Elimina la necesidad de consenso',
'Permite simulación y validación paralela, mejorando throughput y detectando conflictos antes del commit',
'D',
'En "execute-order-validate", las transacciones se simulan primero (execute), luego se ordenan (order) y finalmente se validan antes del commit (validate). Esto permite paralelización, detección temprana de conflictos y mejor throughput comparado con el modelo secuencial tradicional.'),

(12, '¿Cuál es la diferencia entre "hot staking" y "cold staking" en Proof of Stake?', 
'Hot staking mantiene claves online para validación activa, cold staking delega sin exponer claves privadas', 
'Hot staking usa más electricidad', 
'Cold staking es más rentable', 
'No hay diferencia práctica',
'A',
'Hot staking requiere mantener claves privadas online para validar activamente, exponiendo a riesgos de seguridad. Cold staking permite delegar stake a un validador manteniendo claves privadas offline, combinando seguridad de cold storage con participación en staking.'),

(12, '¿Qué es un "validator set" en sistemas Proof of Stake?', 
'Un conjunto de herramientas para validadores', 
'El grupo activo de validadores autorizados para participar en consenso en un período determinado', 
'Una configuración de hardware específica', 
'Un tipo de smart contract',
'B',
'El validator set es el conjunto de validadores activos que pueden proponer y validar bloques en un período específico (epoch). Su composición puede cambiar basándose en stake, rendimiento, slashing o rotación programada, asegurando descentralización y seguridad del consenso.'),

(12, '¿Cuál es la principal diferencia entre "finality" probabilística y determinística en blockchain?', 
'Probabilística es más rápida', 
'Determinística usa más energía', 
'Probabilística aumenta certeza con más confirmaciones, determinística ofrece certeza inmediata tras consenso', 
'No hay diferencia práctica',
'C',
'Finality probabilística (PoW) aumenta certeza de irreversibilidad con cada confirmación adicional pero nunca es 100% absoluta. Finality determinística (algunos PoS/BFT) garantiza irreversibilidad inmediata una vez alcanzado consenso, proporcionando certeza absoluta sin esperas adicionales.'),

(12, '¿Qué característica distingue a los "light clients" o nodos ligeros de los nodos completos?', 
'Son más rápidos en todas las operaciones', 
'No pueden realizar transacciones', 
'Solo funcionan en dispositivos móviles',
'Solo descargan headers de bloques y usan merkle proofs para verificar transacciones específicas',
'D',
'Los light clients descargan solo block headers (no todas las transacciones) y usan merkle proofs para verificar transacciones específicas cuando es necesario. Esto reduce significativamente los requisitos de almacenamiento y ancho de banda, siendo ideales para dispositivos con recursos limitados.'),

(12, '¿Cuál es la función principal de los "bridge contracts" en interoperabilidad blockchain?', 
'Facilitar transferencia de activos y datos entre diferentes blockchains', 
'Acelerar transacciones dentro de una blockchain', 
'Minar bloques más eficientemente', 
'Reducir gas fees',
'A',
'Los bridge contracts permiten interoperabilidad entre blockchains diferentes, facilitando transferencia de tokens, datos o ejecución de operaciones cross-chain. Pueden ser custodiales (lock-and-mint) o no-custodiales, siendo fundamentales para el ecosistema multi-chain.'),

(12, '¿Qué es el "state rent" propuesto para Ethereum?', 
'Alquiler de servidores para nodos', 
'Un mecanismo para cobrar por almacenamiento persistente de datos en el state, incentivando limpieza', 
'Una nueva criptomoneda', 
'Un tipo de staking',
'B',
'State rent es una propuesta para cobrar fees continuos por mantener datos en el state de Ethereum, incentivando la limpieza de datos no utilizados. Busca controlar el crecimiento del state size que afecta la sincronización de nodos y la descentralización de la red.'),

(12, '¿Cuál es la diferencia entre "optimistic rollups" y "zk-rollups" en layer 2?', 
'Optimistic es más rápido, zk-rollups más seguro', 
'Zk-rollups usa PoW, optimistic usa PoS', 
'Optimistic asume validez y permite challenges, zk-rollups prueban validez criptográficamente', 
'No hay diferencia técnica significativa',
'C',
'Optimistic rollups asumen que las transacciones son válidas por defecto y permiten un período de challenge para disputas. Zk-rollups usan pruebas criptográficas (zero-knowledge) para demostrar validez matemáticamente. Optimistic tiene menor costo computacional pero mayor latencia de finality.'),

(12, '¿Qué problema específico resuelven los "state channels" en escalabilidad blockchain?', 
'Aumentan el tamaño de los bloques', 
'Eliminan la necesidad de consenso', 
'Reducen el número de validadores',
'Permiten múltiples transacciones off-chain entre partes con settlement final on-chain',
'D',
'Los state channels permiten a dos o más partes realizar múltiples transacciones off-chain, registrando solo el estado inicial y final on-chain. Esto reduce congestión, costos y latencia, siendo ideal para micropagos o aplicaciones que requieren muchas interacciones entre las mismas partes.'),

(12, '¿Cuál es la principal ventaja de usar "deterministic wallets" (HD wallets) frente a wallets tradicionales?', 
'Generan múltiples direcciones de forma determinística desde una sola seed phrase', 
'Son más rápidas en transacciones', 
'Consumen menos energía', 
'No requieren conexión a internet',
'A',
'Las HD wallets (Hierarchical Deterministic) generan múltiples pares de claves de forma determinística desde una seed phrase maestra. Esto permite crear infinitas direcciones para mejor privacidad, organización y backup, ya que toda la wallet se puede recuperar desde una sola frase semilla.'),

(12, '¿Qué es el "nothing at stake" problem en Proof of Stake?', 
'Los validadores no tienen incentivos económicos', 
'No hay suficientes validadores en la red', 
'Los stakes son demasiado pequeños',
'Los validadores pueden validar múltiples cadenas conflictivas sin costo, potencialmente causando forks',
'D',
'El problema "nothing at stake" surge porque validar múltiples cadenas conflictivas en PoS no tiene costo directo (a diferencia del costo energético en PoW). Esto podría llevar a validadores racionales a validar todas las cadenas para maximizar recompensas, causando inestabilidad. Se mitiga con slashing y finality gadgets.');
-- NUEVAS PREGUNTAS AÑADIDAS (71-90)

INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(12, '¿Cuál es la diferencia entre "weak subjectivity" y "objective finality" en blockchain?', 
'Weak subjectivity es más segura que objective finality', 
'Objective finality es más lenta', 
'Weak subjectivity requiere información externa para validar la cadena correcta, objective finality no', 
'Son conceptos idénticos con diferente nomenclatura',
'C',
'Weak subjectivity significa que nuevos nodos necesitan información externa (checkpoints) para determinar la cadena canónica, común en PoS de larga duración. Objective finality permite determinar la cadena correcta solo con el protocolo, sin información externa, típico en PoW donde la cadena más larga es objetivamente correcta.'),

(12, '¿Qué función cumple el "nonce" en una transacción Ethereum además del nonce de minado?', 
'Previene replay attacks asegurando orden secuencial de transacciones por cuenta', 
'Cifra la transacción', 
'Determina el gas price', 
'Identifica el destinatario',
'A',
'El transaction nonce es un contador secuencial por cuenta que previene replay attacks y asegura orden de ejecución. Cada transacción debe usar el siguiente nonce disponible. Si se envía con nonce incorrecto, la transacción será rechazada o quedará pendiente hasta que se procesen las anteriores.'),

(12, '¿Cuál es la principal diferencia entre "account-based" y "UTXO-based" models en blockchain?', 
'Account-based es más rápido', 
'UTXO solo funciona con Bitcoin', 
'No hay diferencia práctica',
'Account-based mantiene balances globales, UTXO rastrea outputs no gastados individualmente',
'D',
'El modelo account-based (Ethereum) mantiene balances como estado global de cuentas. El modelo UTXO (Bitcoin) rastrea outputs de transacciones no gastados individualmente. UTXO ofrece mejor privacidad y paralelización, mientras account-based simplifica smart contracts y estado complejo.'),

(12, '¿Qué es el "long range attack" en Proof of Stake y cómo se mitiga?', 
'Un ataque que dura mucho tiempo', 
'Un ataque donde validadores con stake histórico crean una cadena alternativa desde el pasado', 
'Un ataque de denegación de servicio', 
'Un ataque a la red de internet',
'B',
'En long range attacks, validadores que tenían stake en el pasado pero ya no lo tienen, pueden crear una cadena alternativa desde un punto histórico sin costo actual. Se mitiga con weak subjectivity checkpoints, slashing histórico y finality gadgets que hacen irreversibles ciertos puntos.'),

(12, '¿Cuál es la función principal de los "watchtowers" en Lightning Network?', 
'Almacenar copias de la blockchain', 
'Validar transacciones on-chain', 
'Monitorear canales y penalizar intentos de cierre fraudulento cuando el usuario está offline', 
'Minar bloques más eficientemente',
'C',
'Los watchtowers monitorizan canales de Lightning Network en nombre de usuarios que pueden estar offline. Si detectan un intento de cierre fraudulento (publicar estado antiguo), pueden transmitir la transacción de penalización correspondiente, protegiendo los fondos del usuario honesto.'),

(12, '¿Qué diferencia existe entre "hard fork" y "soft fork" en términos de compatibilidad?', 
'Hard fork es permanente, soft fork es temporal', 
'Soft fork es más peligroso que hard fork', 
'No hay diferencia en compatibilidad',
'Hard fork rompe compatibilidad hacia atrás, soft fork mantiene compatibilidad con nodos antiguos',
'D',
'Un hard fork introduce cambios incompatibles que requieren que todos los nodos se actualicen, creando potencialmente dos cadenas. Un soft fork restringe reglas manteniendo compatibilidad hacia atrás: nodos antiguos siguen funcionando pero pueden no validar completamente las nuevas reglas.'),

(12, '¿Cuál es la principal ventaja de usar "commit-reveal schemes" en blockchain?', 
'Previene front-running permitiendo commits ocultos que se revelan posteriormente', 
'Acelera las transacciones', 
'Reduce gas fees', 
'Mejora la escalabilidad',
'A',
'Los commit-reveal schemes permiten a usuarios hacer commits de valores hasheados (ocultos) en una primera fase, y revelar los valores reales en una segunda fase. Esto previene front-running y manipulación basada en información prematura, siendo útil en subastas, votaciones y juegos.'),

(12, '¿Qué es el "MEV" (Maximal Extractable Value) en Ethereum?', 
'El valor máximo de una transacción', 
'El valor que validadores pueden extraer reordenando, incluyendo o censurando transacciones en un bloque', 
'El costo máximo de gas', 
'El valor total bloqueado en DeFi',
'B',
'MEV es el valor que validadores/mineros pueden capturar manipulando el orden de transacciones, incluyendo arbitraje, liquidaciones y front-running. Puede crear incentivos perversos y afectar la experiencia del usuario, llevando a soluciones como flashbots y PBS (Proposer-Builder Separation).'),

(12, '¿Cuál es la diferencia entre "permissioned" y "permissionless" blockchains en términos de participación?', 
'Permissioned es más rápida', 
'Permissionless es más segura', 
'Permissioned requiere autorización para participar, permissionless permite participación abierta', 
'No hay diferencia práctica',
'C',
'Blockchains permissionless (Bitcoin, Ethereum) permiten participación abierta sin autorización previa. Blockchains permissioned requieren autorización explícita para leer, escribir o validar. Permissioned ofrece mayor control y privacidad, permissionless mayor descentralización y resistencia a censura.'),

(12, '¿Qué función cumple el "difficulty adjustment algorithm" en Proof of Work?', 
'Determina el precio de la criptomoneda', 
'Selecciona qué transacciones incluir', 
'Distribuye recompensas entre mineros',
'Ajusta la dificultad de minado para mantener tiempo constante entre bloques ante cambios de hashrate',
'D',
'El algoritmo de ajuste de dificultad modifica la dificultad de minado basándose en el tiempo real entre bloques vs el tiempo objetivo. Si el hashrate aumenta (bloques más rápidos), aumenta dificultad. Si disminuye, la reduce. Mantiene tiempo promedio constante (10 min en Bitcoin).'),

(12, '¿Cuál es la principal diferencia entre "atomic swaps" y bridges tradicionales?', 
'Atomic swaps permiten intercambio directo peer-to-peer sin intermediarios custodiales', 
'Atomic swaps son más rápidos', 
'Bridges son más seguros', 
'No hay diferencia técnica',
'A',
'Atomic swaps usan contratos de tiempo bloqueado (HTLC) para intercambio directo entre blockchains sin custodios, garantizando que ambas partes reciban sus activos o ninguna lo haga. Los bridges tradicionales a menudo requieren custodios o validadores intermediarios.'),

(12, '¿Qué es el "validator rotation" en sistemas de consenso?', 
'Cambiar la ubicación física de validadores', 
'Cambiar periódicamente qué validadores participan activamente en consenso', 
'Rotar las claves privadas', 
'Cambiar el algoritmo de consenso',
'B',
'Validator rotation cambia periódicamente el conjunto activo de validadores para mejorar descentralización, seguridad y rendimiento. Puede basarse en stake, rendimiento histórico, aleatoriedad o rotación programada, evitando concentración de poder en validadores específicos.'),

(12, '¿Cuál es la función de los "checkpoint blocks" en algunos sistemas blockchain?', 
'Acelerar la sincronización', 
'Reducir el tamaño de la blockchain', 
'Crear puntos de referencia inmutables que previenen reorganizaciones profundas', 
'Mejorar la privacidad',
'C',
'Los checkpoint blocks son puntos de referencia considerados inmutables por el protocolo, previniendo reorganizaciones más allá de ese punto. Mejoran la seguridad contra long-range attacks y permiten que nuevos nodos sincronicen desde checkpoints confiables en lugar del genesis block.'),

(12, '¿Qué diferencia existe entre "transaction finality" y "economic finality"?', 
'Transaction finality es más rápida', 
'Economic finality solo aplica a PoS', 
'Son conceptos idénticos',
'Transaction finality es técnica (irreversibilidad), economic finality considera el costo económico de reversión',
'D',
'Transaction finality se refiere a la irreversibilidad técnica de una transacción. Economic finality considera el costo económico de revertir una transacción: en PoW es el costo de re-minar, en PoS es el stake que sería slashed. Economic finality puede ser más fuerte que la técnica.'),

(12, '¿Cuál es la principal ventaja de usar "BLS signatures" en blockchain?', 
'Permiten agregación eficiente de múltiples firmas en una sola, reduciendo overhead', 
'Son más rápidas de generar', 
'Son más seguras criptográficamente', 
'Consumen menos energía',
'A',
'Las firmas BLS (Boneh-Lynn-Shacham) permiten agregar múltiples firmas en una sola firma agregada que puede verificarse eficientemente. Esto reduce significativamente el overhead en sistemas con muchos validadores (como Ethereum 2.0), mejorando escalabilidad y eficiencia de verificación.'),

(12, '¿Qué es el "grinding attack" en Proof of Stake?', 
'Un ataque de fuerza bruta a claves privadas', 
'Manipular la aleatoriedad del protocolo probando múltiples valores para influir en la selección de validadores', 
'Sobrecargar la red con transacciones', 
'Atacar físicamente el hardware',
'B',
'En grinding attacks, validadores intentan manipular la fuente de aleatoriedad del protocolo (como hashes de bloques) probando diferentes valores hasta obtener un resultado favorable para la selección de validadores. Se mitiga usando fuentes de aleatoriedad más robustas como VDF o commit-reveal schemes.'),

(12, '¿Cuál es la diferencia entre "immediate finality" y "eventual finality"?', 
'Immediate finality es más cara', 
'Eventual finality es más segura', 
'Immediate finality garantiza irreversibilidad instantánea, eventual finality la garantiza tras cierto tiempo/confirmaciones', 
'No hay diferencia práctica',
'C',
'Immediate finality (algunos BFT) garantiza que las transacciones son irreversibles inmediatamente tras el consenso. Eventual finality (PoW, algunos PoS) garantiza irreversibilidad tras un período de tiempo o número de confirmaciones, con probabilidad creciente de seguridad.'),

(12, '¿Qué función cumple el "gas refund mechanism" en Ethereum?', 
'Devuelve gas no utilizado', 
'Reduce el precio del gas automáticamente', 
'Compensa errores en transacciones',
'Incentiva la limpieza del state devolviendo gas por liberar almacenamiento',
'D',
'El gas refund mechanism devuelve gas cuando se liberan recursos del state (como eliminar contratos o limpiar storage). Esto incentiva la limpieza del state y reduce el crecimiento descontrolado. Sin embargo, está limitado para prevenir abuso y ataques de spam.'),

(12, '¿Cuál es la principal diferencia entre "stateful" y "stateless" blockchain clients?', 
'Stateful mantiene todo el state localmente, stateless obtiene state proofs para cada operación', 
'Stateful es más rápido', 
'Stateless es más seguro', 
'No hay diferencia en funcionalidad',
'A',
'Clientes stateful mantienen una copia completa del state (balances, contratos) localmente. Clientes stateless no almacenan state y requieren state proofs (witness data) para cada operación. Stateless reduce requisitos de almacenamiento pero aumenta overhead de red y computación.'),

(12, '¿Qué es el "weak hands problem" en el contexto de staking?', 
'Validadores con poca experiencia técnica', 
'Validadores con hardware insuficiente', 
'Stakers que retiran fondos rápidamente ante volatilidad, reduciendo seguridad de la red', 
'Problemas de conectividad de red',
'C',
'El "weak hands problem" se refiere a stakers que retiran sus fondos rápidamente ante volatilidad de precios o eventos adversos, reduciendo el total staked y potencialmente la seguridad de la red. Se mitiga con períodos de unbonding y incentivos de largo plazo.');
-- NUEVAS PREGUNTAS AÑADIDAS (91-100)

INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(12, '¿Cuál es la principal diferencia entre "proof of history" y otros mecanismos de consenso?', 
'Es más eficiente energéticamente', 
'No requiere validadores', 
'Crea un registro criptográfico verificable del tiempo transcurrido entre eventos', 
'Es más descentralizado',
'C',
'Proof of History (usado en Solana) crea una secuencia criptográfica verificable que demuestra que cierto tiempo ha transcurrido entre eventos, sin depender de timestamps externos. Esto permite ordenamiento determinístico de transacciones y mayor throughput al reducir la comunicación necesaria entre validadores.'),

(12, '¿Qué problema específico resuelven los "fraud proofs" en optimistic rollups?', 
'Permiten desafiar y probar computaciones incorrectas realizadas off-chain', 
'Previenen double spending', 
'Aceleran las transacciones', 
'Reducen gas fees',
'A',
'Los fraud proofs permiten a cualquier observador desafiar computaciones incorrectas en optimistic rollups durante el período de challenge. Si se demuestra fraude, la transacción se revierte y el secuenciador malicioso es penalizado. Esto mantiene seguridad sin requerir re-ejecución de todas las transacciones on-chain.'),

(12, '¿Cuál es la función de los "sequencers" en layer 2 rollups?', 
'Minar bloques en layer 1', 
'Validar smart contracts', 
'Gestionar wallets de usuarios',
'Ordenar y procesar transacciones off-chain antes de enviar batches a layer 1',
'D',
'Los sequencers reciben, ordenan y procesan transacciones off-chain en rollups, luego envían batches comprimidos a layer 1. Proporcionan confirmación rápida a usuarios y optimizan costos agrupando transacciones. Su centralización es un trade-off temporal por eficiencia, con planes de descentralización futura.'),

(12, '¿Qué es el "data availability problem" en blockchain scaling?', 
'Falta de datos históricos', 
'El desafío de asegurar que datos necesarios para verificar transacciones estén disponibles para todos los nodos', 
'Problemas de conectividad de red', 
'Falta de espacio de almacenamiento',
'B',
'El data availability problem surge cuando nodos necesitan datos para verificar transacciones pero estos no están disponibles (por censura, fallas o ataques). Es crítico en layer 2 y sharding. Se aborda con data availability sampling, erasure coding y comités de disponibilidad de datos.'),

(12, '¿Cuál es la diferencia entre "validity proofs" y "fraud proofs" en layer 2?', 
'Validity proofs son más rápidos', 
'Fraud proofs son más seguros', 
'Validity proofs demuestran corrección criptográficamente, fraud proofs permiten desafiar incorrecciones', 
'No hay diferencia técnica',
'C',
'Validity proofs (zk-rollups) demuestran matemáticamente que las computaciones son correctas usando criptografía zero-knowledge. Fraud proofs (optimistic rollups) asumen corrección pero permiten desafíos durante un período de disputa. Validity proofs ofrecen finality más rápida pero mayor costo computacional.'),

(12, '¿Qué función cumple el "beacon chain" en Ethereum 2.0?', 
'Almacena todas las transacciones', 
'Ejecuta smart contracts', 
'Maneja pagos de gas',
'Coordina la red PoS, gestiona validadores y proporciona aleatoriedad para el consenso',
'D',
'La Beacon Chain es la columna vertebral de Ethereum PoS que coordina validadores, gestiona staking/slashing, proporciona aleatoriedad para selección de validadores y mantiene el consenso. No procesa transacciones directamente sino que coordina la red y prepara para sharding futuro.'),

(12, '¿Cuál es la principal ventaja de usar "verkle trees" sobre merkle trees en blockchain?', 
'Permiten proofs más pequeños para múltiples valores, mejorando eficiencia de stateless clients', 
'Son más rápidos de calcular', 
'Ofrecen mejor seguridad criptográfica', 
'Consumen menos memoria',
'A',
'Los Verkle trees usan compromisos vectoriales que permiten proofs más pequeños cuando se verifican múltiples valores simultáneamente. Esto es especialmente útil para stateless clients que necesitan proofs de múltiples elementos del state, reduciendo significativamente el overhead de datos.'),

(12, '¿Qué es el "proposer-builder separation" (PBS) en Ethereum?', 
'Separar validadores por geografía', 
'Separar la construcción de bloques de su propuesta para reducir MEV y mejorar descentralización', 
'Dividir smart contracts en módulos', 
'Separar layer 1 de layer 2',
'B',
'PBS separa el rol de construir bloques (builders especializados) del rol de proponerlos (validadores). Los builders compiten creando bloques optimizados, los validadores eligen el mejor. Esto reduce MEV extraction por validadores y mejora descentralización al especializar roles.'),

(12, '¿Cuál es la función de los "relayers" en sistemas de meta-transacciones?', 
'Almacenar transacciones pendientes', 
'Validar transacciones', 
'Pagar gas fees en nombre de usuarios y ser reembolsados por otros medios', 
'Minar bloques',
'C',
'Los relayers en meta-transacciones pagan gas fees on-chain en nombre de usuarios que firman transacciones off-chain. Pueden ser reembolsados en tokens alternativos, fiat, o mediante modelos de negocio diferentes. Esto mejora UX eliminando la necesidad de que usuarios tengan ETH para gas.'),

(12, '¿Qué problema resuelve el "account abstraction" en Ethereum?', 
'Reduce gas fees', 
'Acelera transacciones', 
'Mejora privacidad',
'Permite que cuentas de usuario tengan lógica personalizada como smart contracts',
'D',
'Account abstraction permite que cuentas de usuario (EOAs) tengan lógica personalizada como smart contracts, habilitando funcionalidades como multisig nativo, recuperación social, pagos de gas en tokens alternativos, y lógica de autorización compleja sin cambios de protocolo fundamentales.'),

(12, '¿Cuál es la diferencia entre "social recovery" y "multi-signature" wallets?', 
'Social recovery usa contactos de confianza para recuperación, multisig requiere múltiples firmas para cada transacción', 
'Social recovery es más rápida', 
'Multisig es más segura', 
'No hay diferencia práctica',
'A',
'Social recovery permite recuperar acceso a una wallet usando un conjunto de "guardianes" de confianza (amigos, familia, servicios) que pueden ayudar a restaurar acceso si se pierden claves. Multisig requiere múltiples firmas para cada transacción. Social recovery optimiza para recuperación, multisig para autorización distribuida.'),

(12, '¿Qué es el "cross-chain communication protocol" y cuál es su principal desafío?', 
'Un protocolo para acelerar transacciones', 
'Permite interacción entre diferentes blockchains, con el desafío de verificar estados remotos de forma confiable', 
'Un sistema de pagos internacionales', 
'Un mecanismo de consenso híbrido',
'B',
'Los protocolos de comunicación cross-chain permiten que diferentes blockchains intercambien información y activos. El principal desafío es verificar de forma confiable el estado de blockchains remotas sin comprometer seguridad, típicamente usando light clients, oracles, o validadores federados.'),

(12, '¿Cuál es la función principal de los "watchers" en sistemas de payment channels?', 
'Observar precios de mercado', 
'Validar transacciones on-chain', 
'Monitorear el estado de canales y detectar intentos de cierre fraudulento', 
'Gestionar liquidez de canales',
'C',
'Los watchers monitorizan continuamente el estado de payment channels para detectar intentos de publicar estados antiguos o fraudulentos. Cuando detectan fraude, pueden transmitir transacciones de penalización para proteger a la parte honesta, siendo esenciales para la seguridad de canales cuando los usuarios están offline.'),

(12, '¿Qué diferencia existe entre "optimistic" y "pessimistic" approaches en layer 2?', 
'Optimistic es más rápido', 
'Pessimistic consume menos recursos', 
'No hay diferencia en seguridad',
'Optimistic asume honestidad y permite challenges, pessimistic verifica todo proactivamente',
'D',
'El enfoque optimistic (optimistic rollups) asume que las computaciones son correctas por defecto y permite un período para desafíos. El enfoque pessimistic (zk-rollups) verifica proactivamente cada computación usando pruebas criptográficas. Optimistic tiene menor overhead computacional pero mayor latencia de finality.'),

(12, '¿Cuál es el propósito de los "commitment schemes" en protocolos blockchain?', 
'Permitir comprometerse con un valor sin revelarlo, habilitando protocolos de múltiples fases', 
'Acelerar transacciones', 
'Reducir costos de almacenamiento', 
'Mejorar escalabilidad',
'A',
'Los commitment schemes permiten a una parte comprometerse criptográficamente con un valor sin revelarlo inicialmente. Son fundamentales en protocolos de múltiples fases como subastas, votaciones, y sistemas de aleatoriedad, previniendo manipulación basada en información prematura y habilitando fairness.');
