-- Preguntas Tema 13: Desarrollo de contratos inteligentes
-- Generadas: 2025-01-23
-- Total: 50 preguntas difíciles con explicaciones

INSERT INTO preguntas (id_tema, texto, opcion_a, opcion_b, opcion_c, opcion_d, correcta, explicacion) VALUES
(13, '¿Qué es un smart contract?', 
'Un contrato legal en formato digital', 
'Un programa autoejectable en blockchain que ejecuta términos acordados cuando se cumplen condiciones predefinidas', 
'Un documento PDF firmado digitalmente', 
'Un acuerdo verbal entre partes',
'B',
'Un smart contract es código ejecutable en blockchain que se ejecuta automáticamente cuando se cumplen condiciones programadas. Elimina intermediarios, es inmutable, transparente y determinista. Introducido por Nick Szabo (1994), popularizado por Ethereum.'),

(13, '¿Qué es Solidity?', 
'Un tipo de blockchain', 
'Un lenguaje de programación orientado a objetos para escribir smart contracts en Ethereum', 
'Un exchange de criptomonedas', 
'Un algoritmo de consenso',
'B',
'Solidity es el lenguaje más popular para smart contracts en Ethereum. Sintaxis similar a JavaScript/C++, tipado estático, soporta herencia, librerías y tipos complejos. Compila a bytecode EVM. Versión actual: 0.8.x con mejoras de seguridad.'),

(13, '¿Qué es la EVM (Ethereum Virtual Machine)?', 
'Un servidor físico de Ethereum', 
'Una máquina virtual Turing-completa que ejecuta bytecode de smart contracts de forma determinista', 
'Un wallet de Ethereum', 
'Un tipo de token',
'B',
'La EVM es el entorno de ejecución para smart contracts en Ethereum. Es Turing-completa, aislada (sandboxed), determinista (mismo input = mismo output) y ejecuta bytecode. Cada nodo ejecuta la EVM, garantizando consenso en el estado global.'),

(13, '¿Qué es el bytecode en el contexto de smart contracts?', 
'Código fuente en Solidity', 
'La representación compilada de bajo nivel del smart contract que ejecuta la EVM', 
'Un tipo de criptomoneda', 
'Un protocolo de red',
'B',
'El bytecode es el código máquina de la EVM generado al compilar Solidity. Es hexadecimal, optimizado y lo que realmente se almacena/ejecuta en blockchain. Los desarrolladores escriben en Solidity, pero la EVM ejecuta bytecode. Irreversible una vez desplegado.'),

(13, '¿Qué es el ABI (Application Binary Interface) de un smart contract?', 
'Un tipo de token', 
'La especificación JSON que define cómo interactuar con el contrato (funciones, parámetros, tipos)', 
'Un algoritmo de cifrado', 
'Un protocolo de consenso',
'B',
'El ABI es la interfaz que describe las funciones públicas del contrato, sus parámetros y tipos de retorno en formato JSON. Permite a aplicaciones externas (web3.js, ethers.js) codificar llamadas y decodificar respuestas. Esencial para interacción off-chain con contratos.'),

(13, '¿Qué es un "constructor" en Solidity?', 
'Una función que se ejecuta cada vez que se llama al contrato', 
'Una función especial que se ejecuta una sola vez durante el despliegue del contrato', 
'Un tipo de variable', 
'Un modificador de acceso',
'B',
'El constructor es una función opcional que se ejecuta únicamente al desplegar el contrato. Se usa para inicializar estado (variables, owner, parámetros). Desde Solidity 0.5.0 se declara con "constructor()" en lugar del nombre del contrato. No puede ser llamado después del despliegue.'),

(13, '¿Qué son los "modifiers" en Solidity?', 
'Variables que modifican el estado', 
'Código reutilizable que puede cambiar el comportamiento de funciones, típicamente para validaciones', 
'Tipos de datos especiales', 
'Funciones privadas',
'B',
'Los modifiers son fragmentos de código que se ejecutan antes/después de funciones. Comúnmente usados para validaciones (onlyOwner, nonReentrant). Usan "_;" para indicar dónde se ejecuta la función modificada. Mejoran legibilidad y reutilización de lógica de control de acceso.'),

(13, '¿Qué es el modificador "view" en una función Solidity?', 
'Permite modificar el estado del contrato', 
'Indica que la función solo lee estado sin modificarlo, no consume gas cuando se llama externamente', 
'Hace la función privada', 
'Permite recibir Ether',
'B',
'Las funciones "view" prometen no modificar estado (no escribir variables, emitir eventos, crear contratos, etc.). No consumen gas cuando se llaman externamente (off-chain). Sí consumen gas si son llamadas por otra función en una transacción. Reemplazan "constant" en versiones antiguas.'),

(13, '¿Qué es el modificador "pure" en Solidity?', 
'Permite modificar cualquier variable', 
'Indica que la función no lee ni modifica estado, solo opera con parámetros de entrada', 
'Hace la función pública', 
'Permite destruir el contrato',
'B',
'Las funciones "pure" son más restrictivas que "view": no leen ni modifican estado. Solo operan con parámetros y variables locales. Útiles para cálculos matemáticos, validaciones, conversiones. No consumen gas cuando se llaman externamente. Garantizan ausencia de side effects.'),

(13, '¿Qué es el modificador "payable" en Solidity?', 
'Hace que la función sea gratuita', 
'Permite que la función reciba Ether junto con la llamada', 
'Hace que la función pague automáticamente', 
'Elimina el costo de gas',
'B',
'Las funciones "payable" pueden recibir Ether en msg.value. Sin este modificador, transacciones con Ether son rechazadas. Esencial para contratos que manejan pagos, ICOs, marketplaces. El constructor también puede ser payable para recibir fondos iniciales al desplegar.'),

(13, '¿Qué es "msg.sender" en Solidity?', 
'El mensaje enviado en la transacción', 
'La dirección de la cuenta que llamó directamente a la función actual', 
'El destinatario del mensaje', 
'El valor en Ether enviado',
'B',
'msg.sender es una variable global que contiene la dirección que ejecutó la llamada actual. Cambia en llamadas internas entre contratos. Fundamental para control de acceso (verificar owner, permisos). Diferente de tx.origin que siempre es el iniciador original de la transacción.'),

(13, '¿Qué diferencia hay entre "msg.sender" y "tx.origin"?', 
'Son exactamente lo mismo', 
'msg.sender es el llamador inmediato, tx.origin es el iniciador original de la transacción (EOA)', 
'msg.sender es más seguro que tx.origin', 
'tx.origin solo funciona en contratos privados',
'B',
'msg.sender es el llamador directo (puede ser contrato o EOA). tx.origin es siempre la EOA que inició la cadena de llamadas. Usar tx.origin para autenticación es inseguro (vulnerable a phishing). Mejor práctica: usar msg.sender para control de acceso.'),

(13, '¿Qué es "msg.value" en Solidity?', 
'El mensaje de texto enviado', 
'La cantidad de Wei (1 ETH = 10^18 Wei) enviada con la transacción', 
'El valor de retorno de la función', 
'El número de confirmaciones',
'B',
'msg.value contiene la cantidad de Wei enviada con la transacción. Solo disponible en funciones payable. Usado para pagos, depósitos, compras. Importante: trabajar en Wei para evitar errores de precisión. 1 Ether = 1e18 Wei.'),

(13, '¿Qué es "block.timestamp" en Solidity?', 
'La fecha de creación del contrato', 
'El timestamp Unix del bloque actual, manipulable por mineros en ~15 segundos', 
'El tiempo de ejecución de la función', 
'El número de bloque',
'B',
'block.timestamp (antes "now") es el timestamp Unix del bloque actual. Los mineros pueden manipularlo ligeramente (~15 seg), por lo que no debe usarse para lógica crítica de seguridad o aleatoriedad. Útil para timeouts, vesting, pero con precaución.'),

(13, '¿Qué es "block.number" en Solidity?', 
'El número de transacciones en el bloque', 
'El número secuencial del bloque actual en la blockchain', 
'El número de contratos desplegados', 
'El número de validadores',
'B',
'block.number es el índice del bloque actual. Incrementa con cada bloque (~12 seg en Ethereum). Útil para calcular períodos de tiempo aproximados (aunque block time puede variar), implementar vesting basado en bloques, o condiciones temporales más predecibles que timestamp.'),

(13, '¿Qué es un "event" en Solidity?', 
'Una función especial', 
'Un mecanismo de logging que emite datos a los logs de la blockchain, accesibles off-chain', 
'Un tipo de variable', 
'Un modificador de acceso',
'B',
'Los events permiten logging eficiente en blockchain. Se emiten con "emit EventName(params)". Los datos se almacenan en logs (más baratos que storage), indexables y accesibles por aplicaciones off-chain. Esenciales para interfaces de usuario, notificaciones y auditoría. Hasta 3 parámetros pueden ser "indexed".'),

(13, '¿Qué significa "indexed" en un parámetro de event?', 
'Que el parámetro es obligatorio', 
'Que el parámetro puede ser usado como filtro en búsquedas de logs', 
'Que el parámetro es privado', 
'Que el parámetro consume menos gas',
'B',
'Los parámetros "indexed" en events se almacenan en topics, permitiendo búsquedas eficientes. Máximo 3 indexed por event. Tipos complejos (strings, arrays) se hashean. No-indexed van a data section. Crítico para filtrar eventos en dApps (ej: filtrar transferencias por dirección).'),

(13, '¿Qué es "storage" en Solidity?', 
'Un tipo de base de datos externa', 
'El almacenamiento persistente en blockchain donde se guardan variables de estado, muy costoso en gas', 
'La memoria temporal durante ejecución', 
'Un tipo de variable local',
'B',
'Storage es el almacenamiento persistente del contrato en blockchain. Variables de estado se guardan aquí. Extremadamente costoso en gas (20,000 gas para escribir un slot nuevo). Persiste entre llamadas. Modificar storage es la operación más cara en smart contracts.'),

(13, '¿Qué es "memory" en Solidity?', 
'El almacenamiento permanente', 
'Almacenamiento temporal que existe solo durante la ejecución de la función, más barato que storage', 
'Un tipo de blockchain', 
'Una criptomoneda',
'B',
'Memory es almacenamiento temporal durante ejecución de función. Se borra después. Mucho más barato que storage. Usado para variables locales, parámetros de función, arrays temporales. Desde Solidity 0.5.0, debe especificarse explícitamente para tipos complejos (arrays, structs, strings).'),

(13, '¿Qué es "calldata" en Solidity?', 
'Los datos de configuración del contrato', 
'Área de datos inmutable y temporal para parámetros de función external, más eficiente que memory', 
'El historial de llamadas', 
'Un tipo de evento',
'B',
'Calldata es un área de datos read-only para parámetros de funciones external. Más eficiente en gas que memory porque no copia datos. Obligatorio para parámetros de funciones external desde Solidity 0.6.9. Ideal para arrays/strings grandes que solo se leen.'),

(13, '¿Qué es la vulnerabilidad de "reentrancy"?', 
'Cuando un contrato se despliega dos veces', 
'Cuando un contrato malicioso llama recursivamente a una función antes de que complete su ejecución, permitiendo exploits', 
'Cuando se usa demasiada memoria', 
'Cuando el gas es insuficiente',
'B',
'Reentrancy ocurre cuando un contrato externo llama de vuelta a la función original antes de que termine. El ataque más famoso: The DAO (2016, $60M robados). Prevención: patrón Checks-Effects-Interactions, modificador nonReentrant de OpenZeppelin, o usar transfer/send en lugar de call.'),

(13, '¿Qué es el patrón "Checks-Effects-Interactions"?', 
'Un tipo de smart contract', 
'Un patrón de diseño que ordena: 1) validaciones, 2) cambios de estado, 3) llamadas externas, previniendo reentrancy', 
'Un algoritmo de consenso', 
'Un tipo de token',
'B',
'Este patrón previene reentrancy ordenando código: 1) Checks (require/assert), 2) Effects (modificar estado), 3) Interactions (llamadas externas). Actualizar estado antes de llamadas externas evita que reentrancy explote estado inconsistente. Fundamental en seguridad de smart contracts.'),

(13, '¿Qué es "integer overflow/underflow" en Solidity?', 
'Errores de sintaxis', 
'Cuando operaciones aritméticas exceden límites del tipo, causando wrap-around (resuelto en 0.8.0+)', 
'Cuando se usa demasiado gas', 
'Cuando falla el despliegue',
'B',
'Overflow: uint8(255) + 1 = 0. Underflow: uint8(0) - 1 = 255. Antes de Solidity 0.8.0 ocurrían silenciosamente. Desde 0.8.0 revierten automáticamente. Versiones antiguas requerían SafeMath de OpenZeppelin. Crítico en cálculos financieros, balances, timestamps.'),

(13, '¿Qué es "tx.origin phishing attack"?', 
'Un ataque de email', 
'Explotar contratos que usan tx.origin para autenticación, engañando al usuario a llamar contrato malicioso', 
'Un virus informático', 
'Un ataque DDoS',
'B',
'Si un contrato usa "require(tx.origin == owner)" para autenticación, un atacante puede crear contrato malicioso que el owner llame. Como tx.origin sigue siendo owner, el contrato malicioso puede ejecutar funciones privilegiadas. Solución: usar msg.sender siempre.'),

(13, '¿Qué es "selfdestruct" en Solidity?', 
'Una función que pausa el contrato', 
'Una función que destruye el contrato, envía su balance a una dirección y libera storage', 
'Una función que valida datos', 
'Una función que crea nuevos contratos',
'B',
'selfdestruct(address) elimina el bytecode del contrato y envía su balance ETH a la dirección especificada. Libera storage (refund de gas). El contrato deja de funcionar pero su historial permanece en blockchain. Útil para upgrades o emergencias, pero controvertido por implicaciones de seguridad.'),

(13, '¿Qué es un "fallback function" en Solidity?', 
'Una función de respaldo para errores', 
'Una función sin nombre que se ejecuta cuando se llama función inexistente o se recibe Ether sin datos', 
'Una función que siempre falla', 
'Una función de inicialización',
'B',
'La fallback function (ahora separada en fallback() y receive()) se ejecuta cuando: 1) se llama función que no existe, 2) se envía Ether sin datos (si es payable). Limitada a 2300 gas con transfer/send. Útil para recibir pagos o proxy patterns. Debe ser external.'),

(13, '¿Qué es la función "receive" en Solidity 0.6.0+?', 
'Una función para recibir mensajes', 
'Una función especial que se ejecuta cuando el contrato recibe Ether sin datos de llamada', 
'Una función para recibir tokens', 
'Una función de validación',
'B',
'receive() external payable {} se ejecuta cuando se envía Ether puro (sin data) al contrato. Introducida en 0.6.0 separando responsabilidades de fallback. Si no existe receive() pero hay fallback payable, se usa fallback. Más explícito y claro que fallback antiguo.'),

(13, '¿Qué es "delegatecall" en Solidity?', 
'Una llamada normal entre contratos', 
'Una llamada que ejecuta código de otro contrato en el contexto del contrato llamador (mismo storage, msg.sender)', 
'Una llamada que delega permisos', 
'Una llamada asíncrona',
'B',
'delegatecall ejecuta código del contrato B usando storage y contexto del contrato A. msg.sender y msg.value se preservan. Fundamental para proxy patterns y upgradeable contracts. Peligroso si no se entiende: puede sobrescribir storage. Diferente de call que usa contexto del contrato llamado.'),

(13, '¿Qué es un "proxy pattern" en smart contracts?', 
'Un patrón para ocultar código', 
'Un patrón que separa lógica (implementation) de datos (proxy) usando delegatecall, permitiendo upgrades', 
'Un patrón para validar transacciones', 
'Un patrón de minería',
'B',
'El proxy pattern permite upgradeable contracts. El proxy almacena datos y delegatecall a implementation contract con lógica. Para upgrade, se cambia la dirección de implementation. Tipos: Transparent Proxy, UUPS. Complejo pero esencial para contratos que necesitan evolucionar.'),

(13, '¿Qué es OpenZeppelin?', 
'Un exchange de criptomonedas', 
'Una librería de smart contracts seguros y auditados, estándar de facto en la industria', 
'Un tipo de blockchain', 
'Un algoritmo de consenso',
'B',
'OpenZeppelin Contracts es la librería más usada de smart contracts seguros (ERC20, ERC721, Access Control, Security). Código auditado, battle-tested, modular. También ofrece OpenZeppelin Defender (operaciones), Upgrades (proxy patterns). Esencial para desarrollo profesional de contratos.'),

(13, '¿Qué es el estándar ERC-20?', 
'Un tipo de blockchain', 
'El estándar para tokens fungibles en Ethereum, definiendo funciones como transfer, balanceOf, approve', 
'Un algoritmo de consenso', 
'Un tipo de wallet',
'B',
'ERC-20 (Ethereum Request for Comments 20) es el estándar para tokens fungibles. Define interfaz: totalSupply, balanceOf, transfer, transferFrom, approve, allowance. Permite interoperabilidad entre tokens, wallets, exchanges, dApps. Ejemplos: USDT, LINK, UNI. Base de DeFi.'),

(13, '¿Qué es el estándar ERC-721?', 
'Una versión mejorada de ERC-20', 
'El estándar para tokens no fungibles (NFTs), donde cada token es único e indivisible', 
'Un protocolo de seguridad', 
'Un tipo de exchange',
'B',
'ERC-721 define NFTs (Non-Fungible Tokens). Cada token tiene ID único y puede tener metadata diferente. Funciones: ownerOf, transferFrom, approve, tokenURI. Usado para arte digital, coleccionables, gaming, bienes raíces virtuales. Ejemplos: CryptoPunks, Bored Apes, ENS domains.'),

(13, '¿Qué es "gas optimization" en smart contracts?', 
'Llenar el tanque de gas', 
'Técnicas para reducir consumo de gas: usar tipos eficientes, minimizar storage, batch operations', 
'Aumentar el precio del gas', 
'Eliminar funciones',
'B',
'Gas optimization reduce costos de ejecución: 1) Usar uint256 (más eficiente que uint8), 2) Minimizar escrituras a storage, 3) Usar memory/calldata apropiadamente, 4) Batch operations, 5) Usar eventos en lugar de storage para logs, 6) Short-circuit evaluations. Crítico para contratos populares.'),

(13, '¿Qué es "require" en Solidity?', 
'Una función para importar librerías', 
'Una declaración que valida condiciones y revierte la transacción si falla, devolviendo gas no usado', 
'Una función para requerir permisos', 
'Una declaración de variables',
'B',
'require(condition, "error message") valida condiciones. Si falla, revierte todos los cambios y devuelve gas restante. Usado para validar inputs, permisos, estado. El mensaje de error ayuda en debugging. Más eficiente en gas que assert para validaciones de negocio.'),

(13, '¿Qué es "assert" en Solidity?', 
'Una función de logging', 
'Una declaración para verificar invariantes que nunca deberían fallar, consume todo el gas si falla', 
'Una función de transferencia', 
'Una declaración de eventos',
'B',
'assert(condition) verifica invariantes internos que nunca deberían ser falsos. Si falla, consume todo el gas (indica bug serio). Usado para verificar overflow (pre-0.8.0), invariantes matemáticos, estado interno. Diferente de require: assert es para bugs, require para validaciones.'),

(13, '¿Qué es "revert" en Solidity?', 
'Revertir a una versión anterior del contrato', 
'Una declaración que aborta la ejecución y revierte cambios, similar a require pero más flexible', 
'Revertir una transacción después de confirmada', 
'Una función de actualización',
'B',
'revert("mensaje") o revert CustomError() aborta ejecución y revierte cambios. Más flexible que require para lógica compleja. Desde 0.8.4, custom errors son más eficientes en gas que strings. Útil en if/else complejos donde require no es suficiente.'),

(13, '¿Qué son los "custom errors" en Solidity 0.8.4+?', 
'Errores de compilación', 
'Errores definidos por el usuario que son más eficientes en gas que strings en require/revert', 
'Errores de red', 
'Errores de sintaxis',
'B',
'Custom errors (error InsufficientBalance(uint available, uint required)) son más baratos que strings. Se usan con revert: "revert InsufficientBalance(balance, amount)". Ahorran gas significativo, mejoran debugging con parámetros tipados. Mejor práctica moderna vs strings.'),

(13, '¿Qué es "immutable" en Solidity?', 
'Una variable que nunca cambia después de la compilación', 
'Una variable que se asigna en constructor y no puede cambiar después, más barata que storage normal', 
'Una función que no se puede llamar', 
'Un contrato que no se puede destruir',
'B',
'Variables "immutable" se asignan en constructor y son read-only después. Más baratas que storage variables porque se almacenan en bytecode. Útiles para configuración inicial (owner, tokens, direcciones). Introducidas en Solidity 0.6.5. Diferente de "constant" que debe ser literal en compile-time.'),

(13, '¿Qué es "constant" en Solidity?', 
'Una variable que cambia constantemente', 
'Una variable cuyo valor debe ser literal en tiempo de compilación y no consume storage', 
'Una función constante', 
'Un tipo de evento',
'B',
'Variables "constant" deben ser expresiones literales evaluables en compile-time. No consumen storage, se insertan directamente en bytecode. Más baratas que immutable. Útiles para valores fijos (MAX_SUPPLY, DECIMALS). Convención: UPPER_CASE. No pueden ser asignadas en constructor.'),

(13, '¿Qué es un "mapping" en Solidity?', 
'Un mapa geográfico', 
'Una estructura de datos key-value hash table, eficiente pero no iterable', 
'Una función de transformación', 
'Un tipo de array',
'B',
'mapping(keyType => valueType) es una hash table. Acceso O(1), muy eficiente en gas. No iterable (no se pueden listar keys), no tiene length. Todos los keys existen virtualmente (valores default). Común para balances, allowances, ownership. Solo en storage, no en memory.'),

(13, '¿Qué es un "struct" en Solidity?', 
'Una estructura de control', 
'Un tipo de dato personalizado que agrupa variables relacionadas', 
'Una función estructurada', 
'Un tipo de array',
'B',
'Los structs permiten crear tipos complejos agrupando variables. Útiles para organizar datos relacionados (User, Order, Proposal). Pueden contener mappings (solo en storage), arrays, otros structs. Mejoran legibilidad y organización. Se pueden usar en storage, memory y calldata.'),

(13, '¿Qué es "inheritance" en Solidity?', 
'Heredar criptomonedas', 
'Mecanismo que permite a un contrato heredar funciones y variables de contratos padre', 
'Un tipo de transferencia', 
'Un patrón de diseño',
'B',
'Solidity soporta herencia múltiple. "contract Child is Parent1, Parent2" hereda funciones, variables, modifiers. Permite reutilización de código. Usa "virtual" en padre y "override" en hijo para funciones sobrescritas. Orden de herencia importa (C3 linearization). Base de patrones como Ownable, Pausable.'),

(13, '¿Qué es "interface" en Solidity?', 
'La interfaz de usuario', 
'Una definición de contrato que solo declara funciones sin implementación, para interactuar con contratos externos', 
'Un tipo de red', 
'Un protocolo de comunicación',
'B',
'Las interfaces definen funciones sin implementación. Todas las funciones deben ser external. Usadas para interactuar con contratos externos de forma type-safe. No pueden tener constructor, variables de estado, ni herencia de contratos. Ejemplo: IERC20 para interactuar con tokens ERC-20.'),

(13, '¿Qué es "library" en Solidity?', 
'Una colección de libros', 
'Código reutilizable desplegado una vez y usado por múltiples contratos mediante delegatecall', 
'Un tipo de base de datos', 
'Un exchange',
'B',
'Las libraries son contratos especiales sin estado que se despliegan una vez. Funciones internas se copian al contrato, externas usan delegatecall. No pueden tener variables de estado, recibir Ether, ni heredar. Útiles para lógica compartida (SafeMath, Address). Ahorran gas al reutilizar código.'),

(13, '¿Qué es "using for" en Solidity?', 
'Una declaración de uso de gas', 
'Una directiva que adjunta funciones de library a tipos, permitiendo sintaxis de método', 
'Una función de transferencia', 
'Un modificador de acceso',
'B',
'using LibraryName for Type; permite llamar funciones de library como métodos. Ejemplo: "using SafeMath for uint256;" permite "balance.add(amount)" en lugar de "SafeMath.add(balance, amount)". Mejora legibilidad. El primer parámetro de la función library es el tipo.'),

(13, '¿Qué es Hardhat?', 
'Un tipo de hardware wallet', 
'Un entorno de desarrollo para Ethereum con testing, debugging, despliegue y plugins', 
'Un algoritmo de minería', 
'Un exchange',
'B',
'Hardhat es el framework de desarrollo más popular para Ethereum. Ofrece: red local, testing con Mocha/Chai, debugging con console.log en Solidity, despliegue automatizado, plugins extensibles. Reemplazó a Truffle como estándar. Integra con TypeScript, ethers.js, Waffle.'),

(13, '¿Qué es Truffle?', 
'Un tipo de chocolate', 
'Un framework de desarrollo para smart contracts con testing, migración y gestión de redes', 
'Un tipo de token', 
'Un algoritmo de consenso',
'B',
'Truffle fue el primer framework popular para desarrollo Ethereum. Ofrece: compilación, testing, migración, gestión de redes, Truffle Console. Incluye Ganache (blockchain local). Aunque Hardhat es ahora más popular, Truffle sigue siendo usado en proyectos legacy y tiene buena documentación.'),

(13, '¿Qué es Remix IDE?', 
'Un editor de música', 
'Un IDE web para escribir, compilar, desplegar y debuggear smart contracts sin instalación', 
'Un tipo de blockchain', 
'Un exchange',
'B',
'Remix es un IDE basado en navegador para Solidity. No requiere instalación, ideal para aprendizaje y prototipado rápido. Incluye: editor con syntax highlighting, compilador, debugger, análisis estático, plugins, conexión a MetaMask. Perfecto para principiantes y testing rápido.'),

(13, '¿Qué es un "oracle problem" en smart contracts?', 
'Un problema con la base de datos Oracle', 
'El desafío de obtener datos externos confiables en blockchain de forma descentralizada y segura', 
'Un error de compilación', 
'Un problema de gas',
'B',
'Smart contracts no pueden acceder a datos externos directamente. Oracles proveen estos datos, pero introducen punto de centralización y confianza. El oracle problem es: ¿cómo garantizar que datos sean correctos y no manipulados? Soluciones: oracles descentralizados (Chainlink), múltiples fuentes, incentivos económicos.'),

(13, '¿Qué herramienta se usa para verificar contratos en Etherscan?', 
'Un compilador especial', 
'La función "Verify and Publish" que compara bytecode desplegado con código fuente compilado', 
'Un wallet específico', 
'Un tipo de test',
'B',
'Verificar contratos en Etherscan publica el código fuente, haciéndolo transparente y auditable. Se sube código fuente y configuración de compilación. Etherscan compila y compara bytecode. Si coincide, marca el contrato como verificado. Esencial para confianza, permite interacción directa desde Etherscan y muestra funciones/eventos.');




